### ISSUE TITLE
Can not execute Findbugs: One (sub)project contains Java source files that are not compiled

### ISSUE THREAD

**Issue by himanshu-pathak** [spotbugs/sonar-findbugs#1023]
Findbugs failing for a non java project.

[ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:4.0.0.4121:sonar (default-cli) on project <project-name>: Can not execute Findbugs: One (sub)project contains Java source files that are not compiled (/Users/himanshu.pathak/work/code/<project-name>/content).
[ERROR] sonar.java.binaries was set to /Users/himanshu.pathak/work/code/<project-name>/content/target/classes
[ERROR] Sonar JavaResourceLocator.classFilesToAnalyze was empty
[ERROR] -> [Help 1]

## Environment

| Component          | Version |
| ------------------ | ------- |
| SonarQube          | Community EditionVersion 10.4.1 (build 88267) |
| Sonar-FindBugs     | 4.2.9   |
| Maven              | 3.9.6   |
| Java               | 17.0.6 (SonarQube Server) and 17.0.8 (sonar scanner)  |
|scanner  | sonar-maven-plugin:4.0.0.4121|

**Comment by gtoison** [comment]
Hello, in case there are no `.class` files to analyze you can use the `sonar.findbugs.allowuncompiledcode` option, it is described in more details on the landing page of the project: https://github.com/spotbugs/sonar-findbugs

**Comment by himanshu-pathak** [comment]
there are no class files as there are no java files in this project. the project contain node.js code and native js along with other static resources like css, html etc. its not a java project.

looks like a regression similar to https://github.com/spotbugs/sonar-findbugs/issues/504

**Comment by gtoison** [comment]
Normally the plugin does not attempt to analyze the project unless there's at least one source file with extension java, jsp, scala, clj or kt (it analyses several languages, not just java). If one just file was found it looks for compiled .class files

**Comment by himanshu-pathak** [comment]
OK thanks for the help. so there is a jsp file in the code base. but JSPs dont get compiled during the build typically so a class file will never be there in this case. 

sonar.findbugs.allowuncompiledcode helped. But this should qualify as a bug. Right?

**Comment by gtoison** [comment]
That's the expected behaviour, you have some SpotBugs rules enabled in Sonar for the project, and there are some relevant source files, so the plugin expects to find some classes to analyze.
This was done for the case when people do not build their project (so there are no .class files). When that happens ignoring the problem might give a false sense of confidence because no bugs were found

**Comment by himanshu-pathak** [comment]
OK. So if i understand correct, since SonarQube can't analyze JSPs it requires explicit flag so that the users are aware that they are taking an informed decision. Right?

If that's correct, looks like this is a recent improvement. I didn't notice this in SQ 8/9 at-least.

thanks for the help.

**Comment by gtoison** [comment]
I've made change in #1026 to report the languages found in the project, so hopefully the error message should be clearer
