### ISSUE TITLE
Sonatype deploy now requires token authentication

### ISSUE THREAD

**Issue by gtoison** [spotbugs/sonar-findbugs#1027]
Hello @hazendaz 
In relation to https://github.com/spotbugs/spotbugs/discussions/3018 could you please add new `SONATYPE_USERNAME` and `SONATYPE_TOKEN` secrets to this project so I can update the build workflow and use them to deploy?

**Comment by hazendaz** [comment]
Added both as noted.

**Comment by hazendaz** [comment]
I think for now we leave this open until you get a chance to use and confirm.

**Comment by gtoison** [comment]
Fixed by #1029, thank you for setting up the token!

**Comment by gtoison** [comment]
Hello @hazendaz 
Would you know why the latest deploy failed? I see 401 errors in https://github.com/spotbugs/sonar-findbugs/actions/runs/9693008333/job/26748076209

**Comment by hazendaz** [comment]
Not sure, how exactly does this work on the java part

server-username: SONATYPE_USERNAME
          server-password: SONATYPE_TOKEN

?

assume something with that in how its passed to maven?

**Comment by gtoison** [comment]
These are used to populate the local maven settings file, which is used by the deploy plugin (so we don't set the credentials in the pom.xml file)
But this change apparently worked in the PR changing the build to use tokens, and then it worked again when merging the PR:
https://github.com/spotbugs/sonar-findbugs/actions/runs/9669203251/job/26675558747

So I don't understand why it's not working now

**Comment by gtoison** [comment]
The deploy worked on this build: https://github.com/spotbugs/sonar-findbugs/actions/runs/9730747853/job/26854406538
So I don't know why the previous one got 401 errors (and the one before that worked)

**Comment by hazendaz** [comment]
Hi @gtoison, sonatype seemed to drop my token last week.  They have been going though various updates and it was old.  Seems others affected by similar issue in same time frame.  So I created new token and added that, the build now seems ok.  Can you give it a try to see if it is working better now?

**Comment by gtoison** [comment]
I have limited connectivity now as I am on holiday but I will try when I return (next week). Thanks for the follow up!
