### ISSUE TITLE
java.lang.OutOfMemoryError 

### ISSUE THREAD

**Issue by siva517** [spotbugs/sonar-findbugs#117]
The builds are getting failed with the error "Can not execute Findbugs: java.lang.OutOfMemoryError: GC overhead limit exceeded -> [Help 1]"  

Attached the error screenshot

![capture](https://user-images.githubusercontent.com/13632332/28321170-8dcb827a-6ba0-11e7-99d8-9006cfc20383.PNG)

The current values in sonar.properties file are 
sonar.web.javaOpts=-Xmx768m -XX:MaxPermSize=160m -XX:+HeapDumpOnOutOfMemoryError
sonar.ce.javaOpts=-Xmx1024m -Xms128m -XX:+HeapDumpOnOutOfMemoryError -Djava.net.preferIPv4Stack=true

**Comment by siva517** [comment]
The plugin we are using is sonar-findbugs-plugin-3.4.4

**Comment by h3xstream** [comment]
@siva517 Alternatively you can configure the FindBugs Maven plugin and Sonar will pickup the existing report. https://github.com/SonarQubeCommunity/sonar-findbugs/releases/tag/3.6.0

**Comment by h3xstream** [comment]
@siva517 Is this specific to SonarQube or this happens in Maven or Gradle integration?
 - https://github.com/spotbugs/spotbugs-gradle-plugin
 - https://github.com/spotbugs/spotbugs-maven-plugin

**Comment by h3xstream** [comment]
I don't think that modifying the sonar.properties will have an effect on the JVM from Maven.

You can configure the memory allocation to increase it using `export MAVEN_OPTS='-Xmx1G -XX:MaxPermSize=256m'`.
https://stackoverflow.com/a/12543969/89769

`[INFO] The final memory: 20Mo` is probably misleading.

**Comment by KengoTODA** [comment]
I'll close this stale issue. Feel free to reopen if necessary.
