### ISSUE TITLE
Missing Java 8 functional interfaces

### ISSUE THREAD

**Issue by frankbenoit** [spotbugs/sonar-findbugs#123]
Hi

I am running findbugs over SonarQube 6.5, 
I get errors like this:

```
11:22:21 The following classes needed for analysis were missing:
11:22:21   applyAsLong
11:22:21   applyAsDouble
11:22:21   apply
11:22:21   accept
11:22:21   compareTo
```

Those are reported without a references to a specific source file or location or sub project name :-/

The names seem to indicate that there is a problem with Java8?

regards
Frank

**Comment by h3xstream** [comment]
This bug should be reported to SpotBugs project directly. https://github.com/spotbugs/spotbugs/issues/new

**Comment by hazendaz** [comment]
closing issue as this is issue with find-sec-bugs and we don't currently support java 8 any longer (or are getting ready to drop it).  There is already an open ticket with find sec bugs.  Therefore there is no value having this listed here as we cannot do anything about it.
