### ISSUE TITLE
sonar-findbugs-plugin newer than 3.3.0 (02-Sep-2015) not found in maven 

### ISSUE THREAD

**Issue by wbean1** [spotbugs/sonar-findbugs#135]
I'm trying to make a reusable SonarQube server image for development teams to use.  They would like to make use of this plugin.  The puppet module I'm using (https://github.com/maestrodev/puppet-sonarqube) pulls plugins down via maven, however the last `sonar-findbugs-plugin` version [published to maven central](https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22org.sonarsource.sonar-findbugs-plugin%22%20AND%20a%3A%22sonar-findbugs-plugin%22) is `3.3.0` from (02-Sep-2015).

could/should newer versions be published?

**Comment by h3xstream** [comment]
I do not have the right to publish new version under `org.sonarsource`

@benzonico @m-g-sonar might be able to configurge travis-ci to publish automatically the latest build version.

**Comment by benzonico** [comment]
Hi @h3xstream ! 

I'm gonna double check that tomorrow but given that @SonarSource is no longer maintaining this plugin I wonder if it would not be a better course of action to change group id of the plugin (maybe through a major version change) in order for community maintainer (ie: you) to get back ownership of maven central publication. 

Happy to hear your thoughts about this.

**Comment by h3xstream** [comment]
Ideally a groupId that I am not the only one able to publish.

`org.sonarqubecommunity.` ...?

**Comment by benzonico** [comment]
That sounds a nice suggestion. so :+1: Go for it.
What could be great is to announce this change on the google group : sonarqube@googlegroups.com and its motivations. So other community maintainers can join the move and contact you for publication of artifacts under this.

**Comment by KengoTODA** [comment]
I'm not so sure about the motivation to put plugin onto central, is it valuable for users who downloads plugin from sonar update center?

If we still need to deploy onto there, it is possible to migrate this project to com.github.spotbugs groupId, I guess that SpotBugs community welcomes this project.

**Comment by h3xstream** [comment]
@KengoTODA This would make perfect sense.
I will try to prepare a release in the next two weeks (3.7). We can change the GroupIp for that release.

The main motivation is deployment automation (I think). I had to deploy automatically Sonar instance with Sonar-FindBugs preconfigured. The easiest way is to drop the latest extensions in the extensions directory.

**Comment by KengoTODA** [comment]
@h3xstream could you let me configure [this travis project](https://travis-ci.org/SonarQubeCommunity/sonar-findbugs)? I want to store secure env variables to it, to enable deployment (both of SNAPSHOT and stable) to Maven repository.

I guess that you need to invite me to this SonarQubeCommunity organization.

**Comment by h3xstream** [comment]
@KengoTODA  I don't have admin right on the project.. I will make a request on the SonarQube forum to give you access.

**Comment by KengoTODA** [comment]
#157 will solve this issue.
