### ISSUE TITLE
Question about includeFilters

### ISSUE THREAD

**Issue by aepfli** [spotbugs/sonar-findbugs#147]
Hi!

Currently i am only able to set excludeFilters via configuration, but as e.g. we do pr analysis on a branch base with the sonar4stash plugin, it would be actually great, to have an includeFilter.

The sonar analysis takes quite some time, and with simply setting the includes to just the changed files of an Pull Request we could reduce the time spend from findbugs. The analysis in this context would be sufficient enough.

So my question is, is there a away to tell sonar-findbugs to only analyse a provided list of files aka includeFilters? Or do i always have to check the whole codebase? Or do you suggest any other solution?

BR
Simon

**Comment by h3xstream** [comment]
FindBugs/SpotBugs does not have an incremental feature.
The current state is that the analysis require all classes to have all the inheritance metadata. Of course it would be possible to skip heavy analysis done on some classes.. in theory.
Short answer: Not possible at the moment.

I am curious about the time of the analysis (compilation excluded) and the scale of the project in number of lines of code.

**Comment by aepfli** [comment]
Thanks for the info:

The project i am trying to approve has 290k lines of code - it is a legacy project and java is "only" 180 lines

the whole sonarqube analysis takes arround 8 to 10 minutes 

i will provide more specific data later on :D

**Comment by aepfli** [comment]
and the issue is the underlying framework I think - as our deployment package reaches 1gb :)

**Comment by h3xstream** [comment]
8 to 10 minutes is actually pretty fast.

I have deal with project of millions of line of code.

To speed-up the analysis, one quick win is disabling the code duplication finder. In some large "legacy" project, it can find too much similar code.

![2017-10-11 11_36_55-general settings](https://user-images.githubusercontent.com/593130/31452717-bf700736-ae7d-11e7-8985-d66527440724.png)
