### ISSUE TITLE
sonar-findbugs 3.6 fails when analyzing module with non-compiled JSPs

### ISSUE THREAD

**Issue by ahubold** [spotbugs/sonar-findbugs#148]
With sonar-findbugs 3.6 I get an error when analyzing a large multi-module build where one module contains only JSP sources that aren't precompiled:

```
[WARNING] Findbugs needs sources to be compiled. Please build project before executing sonar or check the location of compiled classes to make it possible for Findbugs to analyse your (sub)project ...
ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.2:sonar (default-cli) on project cae-preview-webapp: Can not execute Findbugs: One (sub)project contains Java source files that are not compile ...
```

This was not the case with version 3.5.

I know that it's possible to precompile JSPs but in this case I want to ignore them. Looking into the code in FindbugsConfiguration it seems that the intention was to just log a descriptive warning if JSPs weren't precompiled. However, if there are no other Java files in the module, the code throws an exception before.

Method FindbugsConfiguration::hasSourceFiles was changed from 3.5 to 3.6 and now returns true if there are JSP sources. It should only return true in case of JAVA source files - as documented in its Javadoc.

**Comment by h3xstream** [comment]
Good catch. Yes you are right. JSP should be exclude in the `hasSourceFiles()`

https://github.com/SonarQubeCommunity/sonar-findbugs/blob/14b011e098214154e93421955f62abe99cf6443e/src/main/java/org/sonar/plugins/findbugs/FindbugsConfiguration.java#L158-L170

**Comment by kingoleg** [comment]
Is there are work-around? Can we tune maven or sonar-runner configuration to avoid this?

**Comment by gbenmansour** [comment]
I downgraded to 3.5 findbug plugin in SonarQube , but still have the same error. I'm using the maven goal sonar:sonar. Apparently changing downgrading the SonarQube plugin version does not affect the maven goal? Is there a workaround for this problem ?

**Comment by ahubold** [comment]
@kingoleg Sorry, I don't know any workaround and thus downgraded to 3.5

@gbenmansour I cannot reproduce the issue with version 3.5 and the bug in the source code was introduced with 3.6. Maybe your problem is slightly different and has another cause.

**Comment by kingoleg** [comment]
@ahubold 

I found several workarounds:

1. Add some useless java class to a maven sub-module
2. Exclude all java/jsp/etc files, the plugin needs, from a maven sub-module

Currently I use the 2nd. As the problematic maven sub-module has only 1 *.jsp and no other files the plugin works with.

I thoughts about specify or force the list of language for a maven sub-module for sonar, but it looks like there is no such option

**Comment by mikesullivan63** [comment]
@h3xstream I don't want to be a pest, but is there an estimated date for the 3.7 release?  We've been unable to test some of our projects due to this.

**Comment by benzman81** [comment]
Same here. Needing a fix.

**Comment by ktor** [comment]
Same here. Any target date for the fix?

**Comment by mgortzak** [comment]
Downgrading from 3.6.0 to 3.5.0 worked for me too. I'm also eagerly waiting for the 3.7.0 release.

**Comment by soninob** [comment]
+1 waiting for 3.7

**Comment by mkaun** [comment]
+1waiting for 3.7

**Comment by h3xstream** [comment]
#169 was integrated.
Bonus: There is a new configuration #56 to avoid some blocker for complex projects that are not fully compiled yet.

**Comment by h3xstream** [comment]
The version 3.7.0 is available in a prerelease form : https://github.com/spotbugs/sonar-findbugs/releases/tag/3.7.0 (SonarQube GG https://groups.google.com/forum/#!topic/sonarqube/2DGGjoMfDSc)

**Comment by h3xstream** [comment]
The official release for the official marketplace will be trigger next week.

**Comment by ahubold** [comment]
I haven't tested the new version in detail yet, but I can successfully analyze our project, which means that this bug is fixed.
