### ISSUE TITLE
How to Run Findbugs Analysis for a project with multiple source directories

### ISSUE THREAD

**Issue by Ron4326** [spotbugs/sonar-findbugs#150]
I have one multimodule maven project where there are source directories apart from 'src' where java file resides.

This is the folder structure

    folder1
    	-pom.xml
	
pom.xml Contains modules defined like this:

    <modules>
    	<module>module1</module>
    	<module>module2</module>
    	<module>module3</module>
    	<module>module4</module>
    	<module>module5</module>
    	<module>module6</module>
    	<module>module7</module>
    	<module>module8</module>
    	<module>module9</module>
    	<module>module10</module>
    </modules>

Different modules are organized like this:

    module1
    	-src
    	-gen
    
    module2
    	-src
    	
    module3
    	-gen
    	
    module4
    	
    module5
    	-src
    	-gen
	

So, as you see, there are modules/projects which have either src or gen or both or doesn't have any of it.

When I run findbugs analysis, it picked only java classes from 'src' and skipped 'gen' (Natural as Maven model forces the analyzer to pick from only src)

So, in the Jenkins job configuration, I defined sources explicitly like this:

    -Dsonar.sources=src,gen
    -Dsonar.exclusions=src/test/java/**

When I run with this configuration, analysis fails for modules which doesn't have both src and gen. (module2, module3, module4)

Multiple source directories are defined under maven-build-helper plugin
```
<configuration>
	<sources>
		<source>gen/main/java</source>
	</sources>
</configuration>
```

So, how do I run the analysis to pick either src or gen or skip that module if either of them is not found ?

Thanks,
Ron

**Comment by h3xstream** [comment]
In the latest version, all source directory should be supported. All `.java` are index by Sonar, the current extension search in all those files, the `gen/main/java` should be taken into account.
