### ISSUE TITLE
include find-sec-bugs 1.8 in sonar-findbugs 3.7

### ISSUE THREAD

**Issue by bradflood** [spotbugs/sonar-findbugs#155]
We have a specific interest in using some find-sec-bugs 1.8 features in sonarqube analysis. Is the intent to release find-sec-bugs 1.8 first, and then include it sonar-findbugs 3.7?

**Comment by h3xstream** [comment]
Find-Sec-Bugs 1.8 is not release yet. It will be integrated release and integrate by the end of the year.
