### ISSUE TITLE
Upgrade fb-contrib to 7.2.0?

### ISSUE THREAD

**Issue by adamzovits** [spotbugs/sonar-findbugs#159]
Just a quick question: is the upgrade of fb-contrib to [7.2.0 (released on 2017-12-27)](https://github.com/mebigfatguy/fb-contrib/releases) planned for the near future? If yes, when? Or could a newcomer like me assist in this process? Thank you!

**Comment by h3xstream** [comment]
The version 3.7.0 is available in a prerelease form : https://github.com/spotbugs/sonar-findbugs/releases/tag/3.7.0 (SonarQube GG https://groups.google.com/forum/#!topic/sonarqube/2DGGjoMfDSc)
