### ISSUE TITLE
Make path to existing FindBugs report configurable

### ISSUE THREAD

**Issue by alapshin** [spotbugs/sonar-findbugs#163]
Ability to reuse existing FindBugs report is great and I want to thank you for introducing this feature.
It allows to reduce time spent running SonarQube step, especially if project already executes FindBugs before launching SonarQube. 

However one minor issue with this functionality is that there is seemingly no way to configure path to FindBugs report. Looking into source code this path is hardcoded as `/target/findbugsXml.xml` in
https://github.com/spotbugs/sonar-findbugs/blob/master/src/main/java/org/sonar/plugins/findbugs/FindbugsExecutor.java#L71

It would be great if it was possible to configure this path using properties similar to how `sonar.findbugs.excludesFilters` allows to specify path to exclude filters configuration file.

For now workaround with manually coping existing report to `/target/findbugsXml.xml` seems to work.

**Comment by h3xstream** [comment]
Here is how it will looks like in the Configuration view : 
![2018-03-15 12_21_10-general settings - administration](https://user-images.githubusercontent.com/593130/37476393-6aac6120-284b-11e8-89eb-3f6553830d6d.png)

**Comment by alapshin** [comment]
Looks great.

**Comment by h3xstream** [comment]
The version 3.7.0 is available in a prerelease form : https://github.com/spotbugs/sonar-findbugs/releases/tag/3.7.0 (SonarQube GG https://groups.google.com/forum/#!topic/sonarqube/2DGGjoMfDSc)
