### ISSUE TITLE
Is SonarlInt supported?

### ISSUE THREAD

**Issue by hosszubalazs** [spotbugs/sonar-findbugs#164]
Hey Findbugs team!

Are these rules supported in SonarLint, especially in Eclipse?

Based on the SonarLint Eclipse howto page I see this is a question of official plugin extension vs third party stand-alone plugin. Which one is Findbugs?
https://www.sonarlint.org/eclipse/howto.html

Thanks a lot!

**Comment by h3xstream** [comment]
SonarLint is not linked to SonarQube the backend. It is a wrapper of SonarQuid (for Java).
Unfortunately, It will not include Sonar-FindBugs rules or analyzer that are not embedded by Sonar team.

You can, however, install a plugin for your IDE to run SpotBugs/FindBugs. It will run locally in similar fashion SonarLint does.

**Comment by venkatasatyanarayana** [comment]
Hi Team,

My sonaqube is configured with findbugs
I have Integrated sonarlint eclipse plugin with sonarqube server

Can i see findbug suggestions in eclipse using sonarlint plugin. Is it possible?
If not possible. can you please suggest me eclipse alternative plugin. 

Thank you very much

**Comment by softdevops** [comment]
Hello you can install the plugin **FindBugs** in your IDE , I don't think that **SonarLint** support **FindBugs** as Extension.
