### ISSUE TITLE
Problems while installing Findbugs at the same time as Java plugin

### ISSUE THREAD

**Issue by lucasrudi** [spotbugs/sonar-findbugs#166]
I'm trying to create a new instance of sonarqube using docker. 
To simplify the provisioning I'm instlalling all the plugins at the same time.
While doing it I'm having the following errors:

2018.02.26 14:12:22 WARN web[][o.s.s.p.ServerPluginRepository] Plugin Findbugs [findbugs] is ignored because the required plugin [java] is not installed

2018.02.26 14:13:05 ERROR ce[][o.s.ce.app.CeServer] Compute Engine startup failed
14:13:05
org.sonar.updatecenter.common.exception.PluginNotFoundException: The plugin 'java' required by 'findbugs' is missing.
2018.02.26 14:13:09 WARN app[][o.s.a.p.AbstractProcessMonitor] Process exited with exit value [es]: 143

Is there any way to perform all the installations at once?

sonarqube version: 6.7.1
JAVA plugin 5.1.0.13090
findbugs plugin 3.6.0

**Comment by KengoTODA** [comment]
Please ask to SonarQube community. According to [their google group](https://groups.google.com/forum/#!forum/sonarqube), it is recommended to ask at [SO](https://stackoverflow.com/questions/tagged/sonarqube).
