### ISSUE TITLE
Error Scanning Maven 

### ISSUE THREAD

**Issue by mailitia** [spotbugs/sonar-findbugs#180]
## Issue Description

hello!

I have this error message:

#**Error during SonarQube Scanner execution
org.sonar.squidbridge.api.AnalysisException: Please provide compiled classes of your project with sonar.java.binaries property**

my project is a Maven-java with mysql and the structure is as shown in the images

## Environment

| Component          | Version |
| ------------------ | ------- |
| SonarQube          | 7.0  |
| Sonar-FindBugs     | ?????   |
| Sonar Scanner             | 3.0.3.778-macosx   |
| Java               | ?????   |

![sonar1](https://user-images.githubusercontent.com/2907813/37551660-b53a77b2-2969-11e8-8214-d45a30463c7b.png)
![sonar2](https://user-images.githubusercontent.com/2907813/37551661-b55a11da-2969-11e8-82bf-579e3073bac8.png)

**Comment by h3xstream** [comment]
What is the content of the `target/` folder.
