### ISSUE TITLE
No mapping to source JSP files

### ISSUE THREAD

**Issue by y4ppieflu** [spotbugs/sonar-findbugs#187]
## Issue Description

We have JSPs precompiled with Tomcat Jasper, but the results of analysis in SonarQube are quite ambiguous:
1. When investigating JSP vulnerability there is no mapping to source .jsp file, instead the mapping is made to .java file produced by Jasper.
2. Even when using fn:escapeXml JSTL function, FindBugs reports the potential XSS vulnerability.
![image](https://user-images.githubusercontent.com/6201310/40561942-d19ba45a-6067-11e8-8f83-9f464749848b.png)

Is it by design or maybe a result of some misconfiguration?

## Environment

| Component          | Version |
| ------------------ | ------- |
| SonarQube          | 6.7   |
| Sonar-FindBugs     | 3.6.0   |
| Java               | 1.8   |

**Comment by h3xstream** [comment]
At the moment, it prefers mapping to `.java` over `.jsp`.

This could be changed to mapped JSP when the file name matches generated source code.

**Comment by y4ppieflu** [comment]
h3xstream, thank you. So, now I have i.e. header.jsp -> header_jsp.java -> header_jsp.class. If I rename header_jsp.class to header.class, Sonar will prefer jsp source, right?

**Comment by h3xstream** [comment]
@y4ppieflu If you remove the generated class "*_jsp.java". This should temporarily fix this.

Quick flash: The ".java" file is lookup first because it is the most common. The alternate mapping checks which are basically a series of guesses. They are more time consuming because of the number of variations.

**Comment by y4ppieflu** [comment]
@h3xstream OK, got it, will try. Should .class file be placed in some specific folder in order findsecbugs to find it or it doesn't matter?

**Comment by h3xstream** [comment]
Scriplet are expression evaluated at runtime. Think of an eval function.. It will be supported at some point.
