### ISSUE TITLE
java.lang.IllegalStateException: Can not execute Findbugs

### ISSUE THREAD

**Issue by msaraf1** [spotbugs/sonar-findbugs#188]
## Environment

| Component          | Version |
| ------------------ | ------- |
| SonarQube          | ?????   |
| Sonar-FindBugs     | ?????   |
| Maven              | ?????   |
| Gradle             | ?????   |
| Java               | ?????   |

## Code (If needed)

```java
public class BugSample1 {
  public static void hello(String message) {
       
    //Something
    Runnable r = () -> System.out.println(message);
   
    r.run();
  }
}
```

**Comment by h3xstream** [comment]
Duplicate #189
