### ISSUE TITLE
java.lang.IllegalStateException: Can not execute Findbugs

### ISSUE THREAD

**Issue by msaraf1** [spotbugs/sonar-findbugs#189]
## Environment

| Component          | Version |
| ------------------ | ------- |
| SonarQube          | 6.0   |
| Sonar-FindBugs     | 3.4.4/3.4.3/3.5/3.6   |
| Maven              |    |
| Gradle             | ?????   |
| Java               | 1.8   |

## Code (If needed)

```java
public class BugSample1 {
  public static void hello(String message) {
       
    //Something
    Runnable r = () -> System.out.println(message);
   
    r.run();
  }
}
```

**Comment by h3xstream** [comment]
Please specify the version of the plugin you use.

The complete ouput (masked or not) would be helpful. The IllegalStateException should be followed by a child exception.
https://github.com/spotbugs/sonar-findbugs/blob/09feb543070db4f84cd97de04fcb982efc3d2751/src/main/java/org/sonar/plugins/findbugs/FindbugsExecutor.java#L188

**Comment by KengoTODA** [comment]
I'll close this stale issue. Feel free to reopen if necessary.
