### ISSUE TITLE
Need help with focused Sonar / Findbugs Analysis

### ISSUE THREAD

**Issue by FDartora** [spotbugs/sonar-findbugs#193]
Good morning,

I have some troubles when focusing the Sonar Analysis on some modules (rather than on the whole project) conbined with the use of findbugs.
Here are the informations concerning my work environnement and the configuration I tried until now :

Language analyzed is java. Our sonar analysis is launched by the following maven command, applyed on the super pom (at the root of our project) :
```
MAVEN_COMMAND="${MAVEN_EXEC} -s ${MAVEN_SETTINGS} -gs ${MAVEN_SETTINGS} -B -U sonar:sonar -Dmaven.repo.local=${MAVEN_REPO_LOCAL} -f pom.xml -Dsonar.analysis.mode=issues -Dsonar.skipPackageDesign=true -Dsonar.host.url=http://*****/sonar
```

In order to focus the analysis on modified projects only, I added some properties to the command,such as :
```
-Dsonar.sources, with the absolute path to the modified classes in the analyzed review
-Dsonar.exclusions=/src/test/java//.java,/tests//.java’
-Dsonar.java.binaries, with the absolute path of the “target/classes” directories (compiled code) of all modified modules, separated by commas
-Dsonar.java.libraries, with the absolute path of the internal and external libraries of our application (jars)
```

If this configuration works in the way that it performs the Sonar Analysis and detects the rules activated in the quality profile, the problem is the following :
For each analysis, we spend a lot of time generating findbugs output reports (from 2 to 5 minutes per report) . When the review modifies only 1 module (1 java class), it exports 5 findbugs reports, taking 10 minutes in total. However, when the review modifies 10 modules (1 java class from 10 different modules), the analysis exports 18 findbugs reports, which takes 1 hour !

Thus,

Why the findbugs output report is so time-consuming, and why does the analysis exports more reports than the number of modified modules (eg 5 reports for 1 modified class) in my review ?

Is there a way to deactivate the findbugs output report generation ? (I tried to use a quality profile without findbugs rules activated, and to add the properties `-Dfindbugs.enable=false -Dfindbugs.findbugsXmlOutput=false -Dfindbugs.xmlOutput=false to the maven command but it didn’t work)`

If I pass only the sonar.sources property and the sonar.java.binaries property filed with the jars directory, sonar analysis fails saying it can’t find compilated classes. Why am I forced to pass the “target/classes” directories for the analysis, rather than the jars directory ?

Many thanks for your time and your help. Tell me if you need additionnal informations or more precised explanations.

Versions used:
> SonarQube: 6.5
> sonar-maven-plugin: 3.4.0.905
> sonar-findbugs-plugin: 3.6.0
> sonar-java-plugin: 4.15.0.12310

Best Regards
FDartora

**Comment by h3xstream** [comment]
Sonar configuratioh is just a filter on the result of findbugs.

# Option 1: Run spotbugs prior to sonar

If you want specialize scanning configuration, you can run spotbugs and sonar after. The sonar plugin will use existing results.

```
mvn spotbugs:spotbugs
mvn sonar:sonar
```

This assume that exclusion are applied in the needed submodule configuration for the spotbugs plugin. See `<excludeFilterFile>` in this configuration example : https://github.com/find-sec-bugs/find-sec-bugs/wiki/Maven-configuration

# Option 2: Exclude Sonar from certain module

You can also exclude sonar from running in certain modules. Just like this but with the sonar plugin instead of findbugs: https://stackoverflow.com/a/14210506/89769
