### ISSUE TITLE
Question about pointing to class files.

### ISSUE THREAD

**Issue by PlatanoBailando** [spotbugs/sonar-findbugs#207]
## Issue Description

I'm trying to run spotbugs within sonarqube as part of calling sonar-scanner.  I'm noticing that it is not possible currently to point to the class files inside the built jars, and instead I need to point to the class files in a flat directory structure.  Is there a particular reason not to allow reading the class files from jar files?  

## Environment

| Component          | Version |
| ------------------ | ------- |
| SonarQube          | 7.1   |
| Sonar-FindBugs     | 3.7.0  |
| Maven              | N/A   |
| Gradle             | N/A   |
| Java               |  8  |

**Comment by h3xstream** [comment]
The aggregation of compiled code is done here : 
https://github.com/spotbugs/sonar-findbugs/blob/9aec596f886d9de6e9b0c1fd62aba778eda77161/src/main/java/org/sonar/plugins/findbugs/FindbugsConfiguration.java#L77-L122


The rule of thumb is that developers are using Gradle or Maven. Jars kept on the code repository _are often dependencies_(1). The final package is generally a jar of the final library/application. In the case of Gradle and Maven standard build option, this jar will contains the same classes as those from build directory. By avoiding the jar, we _avoid duplicates classes_. (2)
Generated code might be presented in final jars .. but I think in most cases we will still have those classes files laying in the build directory somewhere.

I think it is for those reasons but I'm not sure about the exact ones.
