### ISSUE TITLE
Sonar-FindBugs 3.8.0 is incompatible with SonarQube 7.4

### ISSUE THREAD

**Issue by fpavageau** [spotbugs/sonar-findbugs#218]
## Issue Description

The analysis fails with:
```
Execution failed for task ':sonarqube'.
> org.sonar.plugins.findbugs.FindbugsConfiguration has unsatisfied dependency 'class org.sonar.plugins.findbugs.FindbugsProfileExporter' for constructor 'public org.sonar.plugins.findbugs.FindbugsConfiguration(org.sonar.api.batch.fs.FileSystem,org.sonar.api.config.Configuration,org.sonar.api.profiles.RulesProfile,org.sonar.plugins.findbugs.FindbugsProfileExporter,org.sonar.plugins.java.api.JavaResourceLocator)' from org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@42501b25:217<[Immutable]:org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@16c085f1:225<[Immutable]:org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@2c31e1e7:9<[Immutable]:org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@2649ebb9:44<|
```

## Environment

| Component          | Version |
| ------------------ | ------- |
| SonarQube          | 7.4   |
| Sonar-FindBugs     | 3.8.0   |
| Gradle             | 4.10.2   |
| Java               | 8   |

**Comment by KengoTODA** [comment]
reproduced at https://travis-ci.org/spotbugs/sonar-findbugs/jobs/448253782

**Comment by dmatej** [comment]
On 7.3 it was alright. It is broken only on 7.4. I'm trying to fix it but it seems there is another compatibility issue.

**Comment by mdridley** [comment]
Any ETA on this fix?

**Comment by dmatej** [comment]
> Any ETA on this fix?

You can clone my fork of this repo and build it. Or wait for official version ...

**Comment by pethers** [comment]
@dmatej built your fork, and works well with 7.4 at https://www.hack23.com/sonar/dashboard?id=com.hack23.cia%3Acia-all so thanks for the work!

**Comment by tfendt** [comment]
Any official update on this issue? We would rather wait for an official version.

**Comment by KengoTODA** [comment]
solved by 3.9

**Comment by fpavageau** [comment]
Is 3.9.0 supposed to be already released, or is this a work in progress? The release looks empty in the [list of releases](https://github.com/spotbugs/sonar-findbugs/releases), the artifact doesn't exist, and the build of the release commit [failed](https://travis-ci.org/spotbugs/sonar-findbugs/builds/452709016?utm_source=github_status&utm_medium=notification).

**Comment by jangrewe** [comment]
What's the course of action if this is still happening with `sonar-findbugs-plugin-3.9.1.jar` on SonarQube 7.6?

```
> org.sonar.plugins.findbugs.FindbugsConfiguration has unsatisfied dependency 'class org.sonar.api.profiles.RulesProfile' for constructor 'public org.sonar.plugins.findbugs.FindbugsConfiguration(org.sonar.api.batch.fs.FileSystem,org.sonar.api.config.Configuration,org.sonar.api.profiles.RulesProfile,org.sonar.plugins.findbugs.FindbugsProfileExporter,org.sonar.plugins.java.api.JavaResourceLocator)' from org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@262d2efa:88<[Immutable]:org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@40264dc4:473<[Immutable]:org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@72e0937c:51<|
```

**Comment by jangrewe** [comment]
This seems to be relevant to the issue: https://github.com/gabrie-allaigre/sonar-gitlab-plugin/issues/213#issuecomment-459016381

**Comment by ediri** [comment]
Same error here with SonarQube 7.6

`[ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.6.0.1398:sonar (default-cli) on project store-geosearch: org.sonar.plugins.findbugs.FindbugsConfiguration has unsatisfied dependency 'class org.sonar.api.profiles.RulesProfile' for constructor 'public org.sonar.plugins.findbugs.FindbugsConfiguration(org.sonar.api.batch.fs.FileSystem,org.sonar.api.config.Configuration,org.sonar.api.profiles.RulesProfile,org.sonar.plugins.findbugs.FindbugsProfileExporter,org.sonar.plugins.java.api.JavaResourceLocator)' from org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@2becfd4c:134<[Immutable]:org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@76130a29:525<[Immutable]:org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@4438938e:65<| -> [Help 1]
`

**Comment by lukaspj** [comment]
See if this thread gets you anywhere https://community.sonarsource.com/t/unsatisfied-dependency-in-sq-7-6/6244 send to be the same issue, namely RulesProfile getting canned. ActiveRules should be used instead

**Comment by ediri** [comment]
@lukaspj : Should i open a seperate issue?

**Comment by KengoTODA** [comment]
for SQ 7.6, we're going to release version 3.10. See #244

About the `org.sonar.api.batch.ScannerSide`, it seems that we do not need to replace them for now; we can pass compilation with this annotation.
