### ISSUE TITLE
Upgrade dependencies for SonarQube 7

### ISSUE THREAD

**Issue by dmatej** [spotbugs/sonar-findbugs#221]
## Issue Description
When I tried to fix issue #218 in #220, first I tried to update dependencies. The SonarQube 7 has some incompatible changes in package org.sonar.sslr which is renamed and somehow refactored.

## Environment

| Component          | Version |
| ------------------ | ------- |
| SonarQube          | 7.4   |
| Sonar-FindBugs     | 3.9.x?/4.0.0?  |
| Maven              | 3.x.x  |
| Gradle             | ?????   |
| Java               | 8uxxx  |

**Comment by KengoTODA** [comment]
current state: LTS of SonarQube is still v6, so we need to depend on v6 API to support both of LTS and latest.
After SonarSource switch LTS to v7, we can upgrade dependencies to SonarQube API v7.

**Comment by KengoTODA** [comment]
Now 3.10.0~ depends on SonarQube 7.6
