### ISSUE TITLE
get updated java11-compatible version for sonar LTS into marketplace

### ISSUE THREAD

**Issue by davidkarlsen** [spotbugs/sonar-findbugs#228]
From Sonarsource:
"
Findbugs is a community plugin. It means that SonarSource does not have the hand on its roadmap. We expect maintainers of community plugins to ask us to publish their new versions with compatibility information when they are ready. This has not been done yet by the maintainer of Findbugs plugin.

I also check on the community I have see nothing about it. 
May I suggest you to ask your question on one of this location:

Findbugs Github project
or on SonarQube community: https://community.sonarsource.com
Best regards,
Jean-Denis.
"

can you get 3.9.0 into the sonar marketplace so we can upgrade? It's required for java11 support.

**Comment by davidkarlsen** [comment]
Linking https://github.com/spotbugs/sonar-findbugs/issues/226 which is relevant too

**Comment by VinodAnandan** [comment]
@davidkarlsen, for the SonarQube marketplace release, we have to meet the requirements from SonarSource ( https://docs.sonarqube.org/display/DEV/Deploying+to+the+Marketplace ). We have noticed a compatibility issue ( https://github.com/spotbugs/sonar-findbugs/issues/226 ) prior to the request for the feedback submission.  That's the main reason I didn't submit the RFF to the SQ community as it may necessarily provide a good impression. 

But if the community needs the sonar-findbugs 3.9 RFF only with SonarQube 6.7 LTS >= SonarQube 7.3, please let us know. We can also submit the RFF with limited compatibility.

**Comment by davidkarlsen** [comment]
We need it for LTS

**Comment by KengoTODA** [comment]
Maybe we can release 3.9 for LTS-7.3 first, then release 3.9.1 with #227 for LTS-7.4.

**Comment by VinodAnandan** [comment]
@davidkarlsen @KengoTODA  Done :) RFF Submitted - https://community.sonarsource.com/t/rff-sonar-findbugs-3-9-0/4367

**Comment by KengoTODA** [comment]
both 3.9 and 3.9.1 have been published to the marketplace.
