### ISSUE TITLE
Findbugs plugin-3.8.0 in Sonarqube version 7.4 causing error #802

### ISSUE THREAD

**Issue by SreeSusmitha** [spotbugs/sonar-findbugs#229]
## Issue Description

I’m trying to analyse using Sonarqube version 7.4 passing maven goal sonar:sonar and getting the following error which is related to findbugs plugin

org.sonar.plugins.findbugs.FindbugsConfiguration has unsatisfied dependency ‘class org.sonar.plugins.findbugs.FindbugsProfileExporter’ for constructor ‘public org.sonar.plugins.findbugs.FindbugsConfiguration(org.sonar.api.batch.fs.FileSystem,org.sonar.api.config.Configuration,org.sonar.api.profiles.RulesProfile,org.sonar.plugins.findbugs.FindbugsProfileExporter,org.sonar.plugins.java.api.JavaResourceLocator)’ from org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@60f21960:312<[Immutable]:org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@e76b097:233<[Immutable]:org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@3dffc764:9<[Immutable]:org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@58dad04a:50<

| Component          | Version |
| ------------------ | ------- |
| SonarQube          | 7.4   |
| Sonar-FindBugs     | 3.8.0  |
| Maven              | 3.5.4  |
| Gradle             | ?????   |
| Java               | 1.8  |

**Comment by KengoTODA** [comment]
duplicates #226, and will be solved by #227
