### ISSUE TITLE
SCALA_PATH_TRAVERSAL_IN Associated rule not present in SonarQube rules

### ISSUE THREAD

**Issue by MaxiLagos54** [spotbugs/sonar-findbugs#235]
## Description

After install Findbugs (with Find-Sec-Bugs) plugin, the rule associated to SCALA_PATH_TRAVERSAL_IN pattern is not found. It is mentioned on this document http://find-sec-bugs.github.io/bugs.htm, so I guess it should be available, exactly as PATH_TRAVERSAL_IN (for Java) does.

## Environment

| Component          | Version |
| ------------------ | ------- |
| SonarQube          | 7.4   |
| Sonar-FindBugs     | 3.9.0 |

**Comment by KengoTODA** [comment]
This is because 526ca6b29fae2684f86b1deba074a4be8a05b67e excludes `SCALA_PATH_TRAVERSAL_IN ` and several bug patterns explicitly.

@h3xstream @skirge could you share why it was excluded? I've checked #133 but not sure why it is necessary.

**Comment by MaxiLagos54** [comment]
Thanks for the quick answer. I cloned the project and I'm trying at my end.
I have enabled the pattern (I removed it from exclusions list). Also I added some classes to support it, just like JSP rules do, and I'm able to get the rule from sonarqube now.

But it seems it is not working. Is there something I can help with? I'd be glad to collaborate with the project. I read the comments in the mentioned tickets and it seems there are some limitations from sonarqube. Could you give me more details about it?

**Comment by KengoTODA** [comment]
Make sure you copied generated XML into `src/main/resources`. See https://github.com/spotbugs/sonar-findbugs/blob/master/generate_profiles/README.md for detail.

Or we can refer https://github.com/skirge/findsecbugsscala for example, but I'm not so sure about that package.

**Comment by MaxiLagos54** [comment]
I have made the required modifications in sonar-findbugs project to support scala rules, following the project you pointed in the previous comment. I packaged it and integrate it to SonarQube.

I can see the rules in SonarQube now. I added a piece of code with a vulnerability to the project am trying to scan, and the new lines are found by the analysis, but it does not open a new vulnerability issue.

What could I be missing?

PD: I have the code locally, I tried to put this into a new branch in order to be able to show you, but it seems I'm not allowed to create branches and push code.

**Comment by KengoTODA** [comment]
please try to fork this repo into your account, then you can push branch and submit PR.

**Comment by MaxiLagos** [comment]
It is not a PR, but I just wanted you to take a look to the code before I submit a pull request https://github.com/MaxiLagos/sonar-findbugs/commit/1d095622057b9e8140fa1ec10e5bd740ccaed46f

As I said before, it is mostly done, but still not getting the vulnerabilities, despite it recognize that there are new lines added to the code.

**Comment by MaxiLagos** [comment]
I have created a PR for reviewing https://github.com/spotbugs/sonar-findbugs/pull/237
Please read the comment, thanks.
