### ISSUE TITLE
 Four quality profiles ? 

### ISSUE THREAD

**Issue by JerryWang304** [spotbugs/sonar-findbugs#239]
After I install sonar-findbugs-plugin.jar, there shows up four quality profiles. Why ? And I notice the sum of each profile's active rules and inactive rules is 1392, the same. Why some rules are inactive in default ?  

![image](https://user-images.githubusercontent.com/11796555/50483609-7c7bc800-0a27-11e9-8e3a-568974dd6740.png)

## Environment

Sonarqube 7.4

**Comment by h3xstream** [comment]
Different profiles. Different needs.
Building custom profiles are time-consuming for developers and require maintenance on every update.

Security profiles includes security rules.
The minimal profile is the suggested profile for the developers who want to cover medium and high priority only.
etc..

You can always look at the rules to see what the profile included.
