### ISSUE TITLE
FindBugs 3.10 not in sonar marketplace

### ISSUE THREAD

**Issue by shexbeer** [spotbugs/sonar-findbugs#245]
## Issue Description

FindBugs in Version 3.10 is not available in sonar marketplace.
Because this version fixes the current SonarQube Server, FindBugs for current versions is defect.

## Environment

| Component          | Version |
| ------------------ | ------- |
| SonarQube          | 7.6  |
| Sonar-FindBugs     | 3.9.1   |
| Java               | 1.8   |

**Comment by alexsuter** [comment]
Hi. Can I download this somewhere else, meanwhile?

**Comment by KengoTODA** [comment]
Please download from GitHub release page: https://github.com/spotbugs/sonar-findbugs/releases

**Comment by VinodAnandan** [comment]
sonar-findbugs 3.10.0  is now available in the market place - https://community.sonarsource.com/t/new-release-sonar-findbugs-3-10-0/6681

**Comment by KengoTODA** [comment]
Thanks VinodAnandan!
