### ISSUE TITLE
Can not execute Findbugs with a timeout threshold value of 600000 milliseconds

### ISSUE THREAD

**Issue by senthilpandy** [spotbugs/sonar-findbugs#254]
I am facing the issue: Can not execute Findbugs with a timeout threshold value of 600000 milliseconds
This issue encountered after added Findbugs plugin into sonarqube.

sonarqube-6.7.6
Findbugs 3.9.2
Java 1.8

**With 600000 Timeout:**
INFO: 0/0 source files have been analyzed
INFO: Sensor JavaSquidSensor [java] (done) | time=7560ms
INFO: Sensor FindBugs Sensor [findbugs]
INFO: Loading findbugs plugin: /Cisco/dcnm_repo/dcnm_new/nms/com/cisco/dcbu/vinci/utils/.scannerwork/findbugs/findsecbugs-plugin.jar
INFO: Findbugs output report: /Cisco/dcnm_repo/dcnm_new/nms/com/cisco/dcbu/vinci/utils/.scannerwork/findbugs-result.xml
INFO: ------------------------------------------------------------------------
INFO: EXECUTION FAILURE
INFO: ------------------------------------------------------------------------
INFO: Total time: 10:24.412s
INFO: Final Memory: 2880M/3730M
INFO: ------------------------------------------------------------------------
ERROR: Error during SonarQube Scanner execution
ERROR: Can not execute Findbugs with a timeout threshold value of 600000 milliseconds
ERROR: 
ERROR: Re-run SonarQube Scanner using the -X switch to enable full debug logging.

**With 7200000 Timeout:**
01:27:46.920 INFO: Findbugs output report: /Cisco/dcnm_repo/dcnm_new/nms/com/cisco/dcbu/vinci/utils/.scannerwork/findbugs-result.xml
02:13:27.194 WARN: [JOURNAL_FLUSHER] WARNING Journal flush operation took 17,253ms last 8 cycles average is 2,156ms
02:20:46.420 WARN: [JOURNAL_FLUSHER] WARNING Journal flush operation took 7,385ms last 8 cycles average is 3,079ms
02:25:49.816 WARN: [JOURNAL_FLUSHER] WARNING Journal flush operation took 37,048ms last 8 cycles average is 7,711ms
02:32:20.710 WARN: [JOURNAL_FLUSHER] WARNING Journal flush operation took 26,867ms last 8 cycles average is 11,069ms

Is there any Fix / Workaround available?

**Comment by senthilpandy** [comment]
This issue persist in following combination also.
sonarqube-7.6
Findbugs 3.10.0 / SpotBugs. 3.1.11

**Comment by HarveyHuiZhang** [comment]
I think the issue can be resolved, refer https://github.com/spotbugs/sonar-findbugs/issues/50

**Comment by smilep** [comment]
As per #50 , it works fine with `Java-Plugin Version 3.14 and Findbugs 3.3`.
Seems like this is an legitimate issue with latest versions of sonar-findbugs where execution time for it has increased manifold and this should be fixed in the sonar-findbugs. Increasing timeout is just a workaround,

**Comment by hazendaz** [comment]
believe this was resolved, so closing.  If still an issue, open a new ticket.
