### ISSUE TITLE
False positive in JSP_INCLUDE

### ISSUE THREAD

**Issue by MattCodd2** [spotbugs/sonar-findbugs#267]
## Issue Description

When analysing JSP files the line 

<jsp:include page="/WEB-INF/jsp/fragment/pageErrors.jsp"/>

is incorrectly flagged as "Dynamic JSP inclusion", which is shown in the example as

<jsp:include page="${param.secret_param}" />

## Environment

| Component          | Version |
| ------------------ | ------- |
| SonarQube          | 7.7.0.23042|
| Sonar-FindBugs     | 3.11.0   |
| Maven              | 3.6.0   |
| Java               | 1.8|

## Code (If needed)

``jsp
<div id="mainContent">

        <form:form modelAttribute="addUserCommand" action="/admin/adminUserAdd.form" name="adminUserAdd" id="adminUserAdd" method="POST"

        autocomplete="off">

            <input type="hidden" name="userScreenName" id="userScreenName" value="adminUserAdd" />

            <input type="hidden" name="action" id="action"/>

            

            <c:set var="showStar" value="true" scope="request"/>

            <jsp:include page="/WEB-INF/jsp/fragment/pageErrors.jsp"/>

Dynamic JSP inclusion could lead to arbitrary code execution

    L55

Dynamic JSP inclusion could lead to arbitrary code execution

    L55

            <jsp:include page="/WEB-INF/jsp/admin/jsp-fragments/UserFields.jsp" />

			<input type="hidden" name="<csrf:tokenname/>" value="<csrf:tokenvalue uri="/admin/adminUserAdd.form"/>"/>

            <button  type="submit" class="hideOnLoad"  id="search" name="search" value="search"><fmt:message key="button.search" /></button>

        </form:form>
```

**Comment by h3xstream** [comment]
Please report the issue here : https://github.com/find-sec-bugs/find-sec-bugs/issues

**Comment by h3xstream** [comment]
Issue created : https://github.com/find-sec-bugs/find-sec-bugs/issues/481
