### ISSUE TITLE
scanForAdditionalClasses misbehaving

### ISSUE THREAD

**Issue by Vampire** [spotbugs/sonar-findbugs#275]
## Issue Description

The `scanForAdditionalClasses` method is misbehaving or at least is buggy.
I have a multi-project build that I analyse with SonarQube through Gradle.
Simplified it is a `core` project, an `fx` project and the actual `app` project.
`fx` depends on `core`, `app` depends on both.

The according SonarQube properties look like
```properties
...
\:core.sonar.java.binaries=...\\core\\build\\classes\\java\\main
\:core.sonar.java.libraries=...\\lib1.jar,...\\lib2.jar
...
\:fx.sonar.java.binaries=...\\fx\\build\\classes\\java\\main
\:fx.sonar.java.libraries=...\\core\\build\\classes\\java\\main,...\\lib1.jar,...\\lib2.jar,...\\lib3.jar,...\\lib4.jar
...
\:app.sonar.java.binaries=...\\app\\build\\classes\\java\\main
\:app.sonar.java.libraries=...\\core\\build\\classes\\java\\main,...\\fx\\build\\classes\\java\\main,...\\lib1.jar,...\\lib2.jar,...\\lib3.jar,...\\lib4.jar,...\\lib5.jar,...\\lib6.jar
...
```

After you called `javaResourceLocator.classFilesToAnalyze()` you have the correct set of source files to be analyzed.
But then you do `scanForAdditionalClasses(...)` for each entry in the class path.
This adds the class files of the dependencies that are given as directory, not as JAR.

This means that the `fx` classes are analyzed twice and the `core` classes are analyzed three times.
For bigger project hierarchies it is even worse of course.
And additionally to the waste of time that is spent in analyzing classes mutliple times, I get reportings of `The following classes needed for analysis were missing` and `The class '...' could not be matched to its original source file. It might be a dynamically generated class.` that are plainly wrong. I for example get the latter one for static inner classes in `core` while `fx` is analysed (because the `core` classes are analyzed again and there cannot be mapped) and I get the former for classes that are used by `core` classes while analyzing `fx`. (The same and more of course when analyzing `app`.)

## Environment

| Component          | Version |
| ------------------ | ------- |
| SonarQube          | 7.5   |
| Sonar-FindBugs     | 3.9.3   |
| Gradle             | 5.3.1   |
| Java               | 11.0.1   |

**Comment by Vampire** [comment]
I'd say this method should not be used at all.
If someone wants the files to get analyzed, he has to add them to `sonar.java.binaries`.
If they are only added to `sonar.java.libraries`, they should only be used to resolve classes, but never being analyzed themselves.

**Comment by jensborrmann** [comment]
We are facing the same issue. Are there any workarounds for this problem?

**Comment by Vampire** [comment]
I don't know, I didn't try it, but I'd guess so.

**Comment by jensborrmann** [comment]
@h3xstream : Can you as the original author of the mentionend code parts (e.g. https://github.com/spotbugs/sonar-findbugs/blob/master/src/main/java/org/sonar/plugins/findbugs/FindbugsConfiguration.java#L95) share some thoughts on that?
IMO in correctly configured Gradle projects this additional scanning is unnecessary. Stuff like precompiled JSPs should simply be added to sonar.java.binaries. This would also ensure that Findbugs behaves more consistent to other Sonar plugins that also rely on the same JavaResourceLocator. 

Maybe there are other usage scenarios where this correct way of parameterization is not possible?

Having a larger multi-project setup this issue causes significant problems to our build times and pollutes the build logs in a nasty way. So help would be appreciated.

**Comment by jensborrmann** [comment]
@KengoTODA : I tried removing the call for scanAdditionalClasses. No breaking tests. 
Of course this could break exisisting functionality that I am not aware of. Is there any chance to get this fixed? Would you even consider accepting a pull request that removes this call?

**Comment by mvegter** [comment]
@KengoTODA do you have an update regarding this?

**Comment by gtoison** [comment]
I've made some integration tests and I'm currently working on one sample JSP project. 
Unfortunately it seems like removing the call to scanForAdditionalClasses() breaks that test, but at least now there are ways to check what's happening.

**Comment by gtoison** [comment]
Hello @Vampire, @jensborrmann and @mvegter 
I made a sample multi-model maven project to try to reproduce the issue but classes only seem to be analyzed once as they should. From what I've seen the classpath of the modules contains the jars of their dependencies, not classes folders.
Now I'm starting to wonder if you are all using gradle, not maven.

I'm not familiar with gradle but (correct me if I'm wrong) I think it speeds up the builds by compiling dependent modules before the jars are built, using the classes folders.
So the behavior might be different whether you are using gradle or maven for a multi module project.

I'm using [SonarQube Orchestrator](https://github.com/SonarSource/orchestrator) for the integration tests and unfortunately it does not seem to support gradle builds, but I could try to extend it

**Comment by Vampire** [comment]
Of course I'm using Gradle. I mentioned that in the original description. ;-)

**Comment by gtoison** [comment]
Fair enough :-) 
But is it correct that dependent modules are not build using the jars of previously built dependencies as it is the case with maven?
Trying to replicate the core/fx/app structure you have I've seen that (with maven) the classpaths contain jars, not source folders. So scanForAdditionalClasses() does not seem to create a problem when building with maven

**Comment by Vampire** [comment]
Yes, that's also correct. Gradle avoids work where it can. And building a jar there would be unnecessary work, so it is not done.

**Comment by gtoison** [comment]
I've made a pull request for this issue: https://github.com/spotbugs/sonar-findbugs/pull/457
The code specific to JSP analysis only executes when there are JSP files in the project.
It would be great if anyone affected by this issue could try it out

**Comment by gtoison** [comment]
The fix for this issue is released here: https://github.com/spotbugs/sonar-findbugs/releases/tag/4.0.6
I will submit it in the market place soon but it would be great if anyone could try it out

**Comment by gtoison** [comment]
Version 4.0.6 has been released in the SonarQube marketplace so please consider upgrading to get the fix for this issue
