### ISSUE TITLE
Can not execute Findbugs: One (sub)project contains Java source files that are not compiled

### ISSUE THREAD

**Issue by zosrothko** [spotbugs/sonar-findbugs#295]
## Issue Description
Hello
I got the error below and would like to know how to get rid of the ERROR (the java source is there in the module but it will never be compiled as it stands for historical reason)

15:37:22 [ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.7.0.1746:sonar (default-cli) on project callout: Can not execute Findbugs: One (sub)project contains Java source files that are not compiled (/root/jenkins/workspace/MIS-CO/CallOut/com.scort.callout.help). -> [Help 1]

## Environment
sonar-maven-plugin:3.7.0.1746
SonarQube version: 7.9.0
Jenkins ver. 2.190.3
Jenkins/FindBugs plugin: 5.0.0
Jenkins/Jacoco plugin: 3.0.4
Jenkins/Maven Integration plugin 3.4
SonarQube Scanner for Jenkins: 2.10
```

**Comment by gtoison** [comment]
Sorry for the belated answer, it should be possible to change the "allow uncompiled code" to get around this issue:

![image](https://user-images.githubusercontent.com/86775455/149833154-9829d3a3-4463-4c7b-a116-b28ae43571d6.png)
