### ISSUE TITLE
Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin

### ISSUE THREAD

**Issue by nandeeshb09** [spotbugs/sonar-findbugs#296]
Hi Team,

we are seeing below issue while analysing the PR.

 Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.4.0.905:sonar (default-cli) on project messaging: PUT https://api.bitbucket.org/2.0/repositories/mediaiq/messaging/pullrequests/169/comments/127155637 returned a response status of 404 Not Found

If we delete this PR , for next PR it will be successful.
For every time , we dont want to delete this PR and try.

Is there any solution for this?

sonarqube version 7.6
 we have this in pom file.
<dependency>
    <groupId>org.codehaus.mojo</groupId>
    <artifactId>sonar-maven-plugin</artifactId>
    <version>3.4.0.905</version>
</dependency>

**Comment by gtoison** [comment]
I don't believe that this is an error with the SonarQube plugin, please feel free to comment here if anything is unclear
