### ISSUE TITLE
Remove duplicates with SonarJava?

### ISSUE THREAD

**Issue by reitzmichnicht** [spotbugs/sonar-findbugs#304]
Is there an interest to get rid of duplicate findbugs rules that are already covered by the SonarJava plugin?

If so I could provide a list of duplicates I already discovered.

**Comment by reitzmichnicht** [comment]
e.g:
- fb-contrib:FII_USE_METHOD_REFERENCE -> java:S1612

**Comment by toniedzwiedz** [comment]
I'm working on updating a company-wide quality profile at the moment and I've been wondering about the same thing. A number of rules appear to have equivalents provided by the Java plugin and those usually have longer, clearer descriptions of each violation, including compliant and non-compliant code samples.

Here's a few more examples I've come across

- `fb-contrib:AFBR_ABNORMAL_FINALLY_BLOCK_RETURN` could be made redundant by having `java:S1143` and/or `java:S1163` enabled
- `fb-contrib:AIOB_ARRAY_STORE_TO_NULL_REFERENCE` seems to overlap with `java:S2259`
- `fb-contrib:SPP_TOSTRING_ON_STRING`  could be replaced by `java:S1858` 
- `fb-contrib:SPP_USE_BIGDECIMAL_STRING_CTOR` coud be dropped in favour of `java:S2111`
- `fb-contrib:SPP_USELESS_TERNARY`  seems like it should be picked by `java:S1125`

In each case, I find the rule provided by the Java Plugin somewhat clearer. It would be super helpful to users if the team could provide some guidance as to what the plan is regarding these rules. Also, if any of the rules is deprecated, their descriptions could point at possible equivalents.

WDYT? Is this something we could help with?

**Comment by gtoison** [comment]
Hello @KengoTODA 
What are your thoughts on that issue?
One way would be to mark these rules as deprecated and maybe someday remove them in a future release?
We would need to confirm that the SQ rule actually supersedes the SpotBugs rule though

**Comment by KengoTODA** [comment]
I personally have no opinion, and the idea to mark them as deprecated seems nice.
