### ISSUE TITLE
Can sonar findbugs plugin support the option `-onlyAnalyze`?

### ISSUE THREAD

**Issue by Saix1020** [spotbugs/sonar-findbugs#308]
We are using sonar to scan an android project, and the sensor findbugs consumed too long time(> 5min).
Check the findbugs(spotbugs), it support -onlyAnalyze, but this option is not supported by sonar findbugs plugin, so I wonder to know if it’s possible to sonar findbugs plugin to support this option?

Thanks

**Comment by gtoison** [comment]
Fixed by https://github.com/spotbugs/sonar-findbugs/pull/483
Please consider upgrading to the latest version to use the new option
