### ISSUE TITLE
Where can I get the matchup version between findbugs-plugin and SonarQube ?

### ISSUE THREAD

**Issue by suoha666** [spotbugs/sonar-findbugs#313]
## Issue Description
for example:
sonar-findbugs-plugin-3.9 requires at least SonarQube 7.6

| Component          | Version |
| ------------------ | ------- |
| SonarQube          | 7.1   |
| Sonar-FindBugs     | sonar-findbugs-plugin-3.4.2.jar   |
| Java               |1.8.0_242 |

**Comment by KengoTODA** [comment]
You can find it in the README.
https://github.com/spotbugs/sonar-findbugs#compatibility

**Comment by suoha666** [comment]
@KengoTODA 
thank u so much!
