### ISSUE TITLE
Can findbugs scan the *.java source code directly?

### ISSUE THREAD

**Issue by yoyoyang888** [spotbugs/sonar-findbugs#314]
## Issue Description
Scan the Java source code(*.java) with FindBugs Security Audit，An error is as follows:
![图片](https://user-images.githubusercontent.com/47739922/81524896-791b7f00-9385-11ea-8b18-65d8d5b66966.png)

## Environment
| Component          | Version |
| ------------------ | ------- |
| SonarQube           | 7.7-SNAPSHOT |
| Sonar-FindBugs    | 4.0.0 |
| Java                      | 1.8 |

**Comment by KengoTODA** [comment]
FindBugs/SpotBugs analyses compiled `.class` files, not `.java` files.
If you want to analyse without compilation, use other solution like [PMD](https://pmd.github.io).
