### ISSUE TITLE
Invalid Class file format for queueAlerts.class

### ISSUE THREAD

**Issue by at133m** [spotbugs/sonar-findbugs#315]
## Issue Description
While scan project with sonarqube, Build is failing with below error message:

ERROR: Error during SonarQube Scanner execution
ERROR: Can not execute Findbugs
ERROR: Caused by: java.lang.RuntimeException: java.io.IOException: IOException while scanning codebases
ERROR: Caused by: java.io.IOException: IOException while scanning codebases
ERROR: Caused by: IOException while scanning codebases
ERROR: Caused by: Invalid classfile format in /opt/app/b2bi/build/dsoaas/zlp24102.vci.att.com_13541/workspace/xg50.0/lib/packages/eCo/code/classes/eCo/SheduleJobs/queueAlerts.class

## Environment
Sonarqube version is 7.9.2,

| Component          | Version |
| ------------------ | ------- |
| SonarQube          | 7.9.2  |
| Sonar-FindBugs     | 4.0.0   |
| Maven              | ?????   |
| Gradle             | ?????   |
| Java               | 1.8.0_121   |

Maven and Gradle are not used.GNU Make 3.81 is used. The javac command is invoked in the Makefiles.

## Code (If needed)

```java
public class BugSample1 {
  public static void hello(String message) {
       
    //Something
    Runnable r = () -> System.out.println(message);
   
    r.run();
  }
}
```

**Comment by gtoison** [comment]
Sorry for the belated answer, I'm running progressively through the backlog of older issues
Unfortunately I won't be able to investigate this without additional information, I'll close this and please don't hesitate to reopen if the issue persists
