### ISSUE TITLE
 Code smell appears despite existing spotbugs exclude filter

### ISSUE THREAD

**Issue by maisonobe** [spotbugs/sonar-findbugs#316]
## Issue Description

We are using SonarQube in an existing maven-multimodule environment, for open source project Hipparchus.

There are spotbugs exclude filters in each module, see for example [clustering exclude filter](https://github.com/Hipparchus-Math/hipparchus/blob/master/hipparchus-clustering/src/conf/spotbugs-exclude-filter.xml), [core exclude filter](https://github.com/Hipparchus-Math/hipparchus/blob/master/hipparchus-core/src/conf/spotbugs-exclude-filter.xml) and several others. All these filters are declared in the Administration → Java → Findbugs → Exclude filters, with relative paths starting from the top level aggregator

However, this does not seem to work. One example among others: [this storage of a mutable array](https://sonar.orekit.org/project/issues?id=org.hipparchus%3Ahipparchus-aggregator&issues=AXDD1u5WyM-o22b-qUj9&open=AXDD1u5WyM-o22b-qUj9) is identified as a code smell, despite it is configured to be ignored in the exclude file. It is intentional, documented, and already configured for other checkers too (for example there is a PMD comment at the start of the method). When the maven site is generated, spotbugs does obey the exclude files (as shown by the [spotbugs report](https://www.hipparchus.org/hipparchus-core/spotbugs.html)), so the files syntax is expected to be good. Only sonar-findbugs does not obey the exclusion files.

I think at least some exclusions are considered because the project analysis is still good (everything set to A and only 34 code smells for a decade old project with more than 100k lines). However, 31 of these 34 code smells really belong to the exclusions we set up. They are all known, intentional, and well documented, so I am annoyed as I fear that the three important ones that are not excluded and new ones that would not be intentional and could creep in later on get unnoticed, hidden by the 31 ones we can’t silence.

## Environment

| Component          | Version |
| ------------------ | ------- |
| SonarQube          | 7.5 community edition  |
| Sonar-FindBugs     | 4.0.0   |
| Maven              | 3.x   |
| Java               | 1.8   |

## Code (If needed)
The SonarQube prject is visible [here](https://sonar.orekit.org/dashboard?id=org.hipparchus%3Ahipparchus-aggregator), the Hipparchus project source code is [here](https://github.com/Hipparchus-Math/hipparchus/)

**Comment by gtoison** [comment]
Sorry for the belated answer, I got involved in the project recently and I'm trying to look into the backlog of issues.
I looked into the code and it seems to me like it should work, however the exclude file might be incorrectly setup and in that case there might be a warning log: `FindBugs filter-file not found: ...`. On the other hand if the exclude file is picked up correctly you should see: `Use filter-file: ...`.

Could you please look into your logs and check which of these messages do you see?

**Comment by tetebueno** [comment]
Hi, I bumped into this issue too and even though I can see the `Use filter-file: ...` line in the logs, my exclude seems to get ignored.

This is the snippet of my excludes file:
```xml
...
<Match>
    <Class name="some.project.path.SomeSpringSecurityConfiguration"/>
    <Method name="configure"/>
    <Bug pattern="SPRING_CSRF_PROTECTION_DISABLED"/>
</Match>
...
```

When I get to the Sonar report I find in the Security Hotspots the "Make sure disabling Spring Security's CSRF protection is safe here". I was expecting this didn't even apppear. Please, let me know if there's something wrong with my expectations or the way is working.

<html>
<body>


Component | Version
-- | --
SonarQube | 8.9.7 (build 52159) community edition
Sonar-FindBugs | 3.11.1
Maven | 3.8.6
Java | 11.0.16


</body>
</html>

**Comment by gtoison** [comment]
Hello, I never got an answer from OP so I'm not sure what might be the problem
Not many people seem to be using the filters when using SpotBugs inside SonarQube, as it is usually more convenient to sort out issues in SonarQube.
Can you please check your analyzer logs? There should be a message about the filter file, maybe it was found?

Also, the version of the plugin is quite old and you SonarQube version is no longer maintained (the LTS version is 8.9). Diagnosing a problem in a version from 2 years ago is not always straightforward

**Comment by tetebueno** [comment]
Hey, thanks for the reply. Unfortunately, I don't control the updating schedule of Sonar, it's on the way, but not in the short term. I'll try to get back when we update everything.

Also, when you mention:
> (...) it is usually more convenient to sort out issues in SonarQube.

Do you mean solving issues through the web UI?

**Comment by tetebueno** [comment]
Sure, here's the filter file:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<FindBugsFilter xmlns="https://github.com/spotbugs/filter/3.0.0"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xsi:schemaLocation="https://github.com/spotbugs/filter/3.0.0 https://raw.githubusercontent.com/spotbugs/spotbugs/3.1.0/spotbugs/etc/findbugsfilter.xsd">
    <Match>
        <!-- Excluding tests. -->
        <Class name="~.*/.*Test" />
        <Class name="~.*/.*IT" />
    </Match>
    <Match>
        <!-- API gateway takes care of this. -->
        <Class name="project.packages.configuration.SecurityConfiguration" />
        <Method name="configure" />
        <Bug pattern="SPRING_CSRF_PROTECTION_DISABLED" />
    </Match>
</FindBugsFilter>
```

And here are some logs of the CI job that executes the `sonar:sonar` Maven goal:
```console
$ mvn $MAVEN_CLI_OPTS sonar:sonar -Dsonar.host.url=$SONAR_URL -Dsonar.login=$SONAR_LOGIN_TOKEN -Dsonar.findbugs.excludesFilters=spotbugs-exclude.xml -Dsonar.qualitygate.wait=true
[INFO] Scanning for projects...
[INFO] 
[INFO] ---------------------< groupi:project-id >----------------------
[INFO] Building project name 0.1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- sonar-maven-plugin:3.9.1.2184:sonar (default-cli) @ project-id ---
[INFO] User cache: /var/maven/.sonar/cache
[INFO] SonarQube version: 8.9.7
[INFO] Default locale: "en", source code encoding: "UTF-8"
[INFO] Load global settings
[INFO] Load global settings (done) | time=240ms
[INFO] Server id: 243B8A4D-AWlS1yko1KfL7usV92wR
[INFO] User cache: /var/maven/.sonar/cache
[INFO] Load/download plugins
[INFO] Load plugins index
[INFO] Load plugins index (done) | time=101ms
[INFO] Load/download plugins (done) | time=1593ms
[INFO] Process project properties
[INFO] Process project properties (done) | time=18ms
[INFO] Execute project builders
[INFO] Execute project builders (done) | time=2ms
[INFO] Project key: groupi:project-id
[INFO] Base dir: /builds/dir/project-id
[INFO] Working dir: /builds/dir/project-id/target/sonar
[INFO] Load project settings for component key: 'groupi:project-id'
[INFO] Load project settings for component key: 'groupi:project-id' (done) | time=25ms
[INFO] Auto-configuring with CI 'Gitlab CI'
[INFO] Load quality profiles
[INFO] Load quality profiles (done) | time=219ms
[INFO] Auto-configuring with CI 'Gitlab CI'
[INFO] Load active rules
[INFO] Load active rules (done) | time=1157ms
[INFO] Indexing files...
[INFO] Project configuration:
[INFO]   Excluded sources for coverage: **/*Exception.*, **/src/main/java/project/packages/configuration/*.*
[INFO] 14 files indexed
[INFO] 0 files ignored because of scm ignore settings
[INFO] Quality profile for java: Sonar way
[INFO] Quality profile for xml: Sonar way
[INFO] ------------- Run sensors on module project name
[INFO] Load metrics repository
[INFO] Load metrics repository (done) | time=32ms
[INFO] Sensor JavaSquidSensor [java]
[INFO] Configured Java source version (sonar.java.source): 11
[INFO] JavaClasspath initialization
[INFO] JavaClasspath initialization (done) | time=12ms
[INFO] JavaTestClasspath initialization
[INFO] JavaTestClasspath initialization (done) | time=2ms
[INFO] Java Main Files AST scan
[INFO] 8 source files to be analyzed
[INFO] Load project repositories
[INFO] Load project repositories (done) | time=33ms
[INFO] 8/8 source files have been analyzed
[INFO] Java Main Files AST scan (done) | time=3979ms
[INFO] Java Test Files AST scan
[INFO] 5 source files to be analyzed
[INFO] 5/5 source files have been analyzed
[INFO] Java Test Files AST scan (done) | time=974ms
[INFO] Java Generated Files AST scan
[INFO] 0 source files to be analyzed
[INFO] 0/0 source files have been analyzed
[INFO] Java Generated Files AST scan (done) | time=0ms
[INFO] Sensor JavaSquidSensor [java] (done) | time=5315ms
[INFO] Sensor CSS Rules [cssfamily]
[INFO] No CSS, PHP, HTML or VueJS files are found in the project. CSS analysis is skipped.
[INFO] Sensor CSS Rules [cssfamily] (done) | time=0ms
[INFO] Sensor JaCoCo XML Report Importer [jacoco]
[INFO] 'sonar.coverage.jacoco.xmlReportPaths' is not defined. Using default locations: target/site/jacoco/jacoco.xml,target/site/jacoco-it/jacoco.xml,build/reports/jacoco/test/jacocoTestReport.xml
[INFO] Importing 1 report(s). Turn your logs in debug mode in order to see the exhaustive list.
[INFO] Sensor JaCoCo XML Report Importer [jacoco] (done) | time=271ms
[INFO] Sensor C# Project Type Information [csharp]
[INFO] Sensor C# Project Type Information [csharp] (done) | time=2ms
[INFO] Sensor C# Properties [csharp]
[INFO] Sensor C# Properties [csharp] (done) | time=1ms
[INFO] Sensor FindBugs Sensor [findbugs]
[INFO] Loading findbugs plugin: /builds/dir/project-id/target/sonar/findbugs/findsecbugs-plugin.jar
[INFO] Findbugs output report: /builds/dir/project-id/target/sonar/findbugs-result.xml
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.thoughtworks.xstream.core.util.Fields (file:/var/maven/.sonar/cache/c9586d90652066b6c83db6723ac0ca72/sonar-findbugs-plugin.jar_unzip/META-INF/lib/xstream-1.4.11.jar) to field java.util.TreeMap.comparator
WARNING: Please consider reporting this to the maintainers of com.thoughtworks.xstream.core.util.Fields
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] Use filter-file: /builds/dir/project-id/spotbugs-exclude.xml
The following classes needed for analysis were missing:
  makeConcatWithConstants
  matches
[INFO] Sensor FindBugs Sensor [findbugs] (done) | time=9509ms
[INFO] Sensor SurefireSensor [java]
[INFO] parsing [/builds/dir/project-id/target/surefire-reports]
[INFO] Sensor SurefireSensor [java] (done) | time=729ms
[INFO] Sensor JavaXmlSensor [java]
[INFO] 1 source file to be analyzed
[INFO] 1/1 source file has been analyzed
[INFO] Sensor JavaXmlSensor [java] (done) | time=152ms
[INFO] Sensor HTML [web]
[INFO] Sensor HTML [web] (done) | time=3ms
[INFO] Sensor XML Sensor [xml]
[INFO] 1 source file to be analyzed
[INFO] 1/1 source file has been analyzed
[INFO] Sensor XML Sensor [xml] (done) | time=122ms
[INFO] Sensor VB.NET Project Type Information [vbnet]
[INFO] Sensor VB.NET Project Type Information [vbnet] (done) | time=1ms
[INFO] Sensor VB.NET Properties [vbnet]
[INFO] Sensor VB.NET Properties [vbnet] (done) | time=1ms
[INFO] ------------- Run sensors on project
[INFO] Sensor Zero Coverage Sensor
[INFO] Sensor Zero Coverage Sensor (done) | time=1ms
[INFO] Sensor Java CPD Block Indexer
[INFO] Sensor Java CPD Block Indexer (done) | time=21ms
[INFO] CPD Executor 2 files had no CPD blocks
[INFO] CPD Executor Calculating CPD for 6 files
[INFO] CPD Executor CPD calculation finished (done) | time=13ms
[INFO] Analysis report generated in 71ms, dir size=156 KB
[INFO] Analysis report compressed in 26ms, zip size=44 KB
[INFO] Analysis report uploaded in 35ms
[INFO] ------------- Check Quality Gate status
[INFO] Waiting for the analysis report to be processed (max 300s)
[INFO] QUALITY GATE STATUS: PASSED - View details on https://sonar.internal:9000/dashboard?id=groupi%3Aproject-id
[INFO] Analysis total time: 25.499 s
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  35.723 s
[INFO] Finished at: 2023-02-01T09:42:56-03:00
[INFO] ------------------------------------------------------------------------
```

**Comment by gtoison** [comment]
Thanks for the details, I'm wondering if the issue might be that `SPRING_CSRF_PROTECTION_DISABLED` is from the findsec-bugs plugin, do you also have exclusion for bugs from the built-in SpotBugs rules?

**Comment by tetebueno** [comment]
You are right, we only use it for FindSec bugs. Do you think I should ping the specific project?

**Comment by gtoison** [comment]
Hum I don't think the issue is with Findsecbugs itself, I didn't know you also had an include file and now I wonder how it interacts with the exclude. I'll try reproducing the problem

BTW, are you sure that this part is correct? My understanding is that the criteria inside a `<Match>` all need to match. I think you should have one Match block for `*Test` and one for `*IT `
```
    <Match>
        <!-- Excluding tests. -->
        <Class name="~.*/.*Test" />
        <Class name="~.*/.*IT" />
    </Match>
```

**Comment by gtoison** [comment]
I made a minimal example to check that the exclude filter works as intended. The include file is not used from what I can see.
Enabling the filter does work for me, can you please check what you might be doing differently?

The sample project is available here:
https://github.com/gtoison/sonar-findbugs/tree/exclude-filter-example/src/test/resources/projects/spring

**Comment by gtoison** [comment]
I'm closing that one since it seems to work as expected
Please do not hesitate to open a new issue if the problem persists

**Comment by tetebueno** [comment]
Sorry for the delay, a lot of things going on at work. We just revisited this (now with plugin version `4.2.3`, since it was updated earlier this year) and I still can't get the XML configuration to remove security hotspots in the Sonar UI.

Now the exclude file looks like this:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<FindBugsFilter xmlns="https://github.com/spotbugs/filter/3.0.0"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xsi:schemaLocation="https://github.com/spotbugs/filter/3.0.0 https://raw.githubusercontent.com/spotbugs/spotbugs/3.1.0/spotbugs/etc/findbugsfilter.xsd">
    <Match>
        <Class name="~.*/.*Test" />
    </Match>
    <Match>
        <Class name="~.*/.*IT" />
    </Match>
    <Match>
        <Class name="project.packages.configuration.SecurityConfiguration" />
        <Method name="configure" />
        <Bug pattern="SPRING_CSRF_PROTECTION_DISABLED" />
    </Match>
</FindBugsFilter>
```

And the include like this:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<FindBugsFilter xmlns="https://github.com/spotbugs/filter/3.0.0"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xsi:schemaLocation="https://github.com/spotbugs/filter/3.0.0 https://raw.githubusercontent.com/spotbugs/spotbugs/3.1.0/spotbugs/etc/findbugsfilter.xsd">
    <Match>
        <Bug category="SECURITY" />
    </Match>
</FindBugsFilter>
```

Also, `pom.xml` file follows [this wiki](https://github.com/find-sec-bugs/find-sec-bugs/wiki/Maven-configuration) to configure the plugin.

Am I missing something? I couldn't find any additional configuration in the `pom.xml` file in the example code you graciously provided [here](https://github.com/spotbugs/sonar-findbugs/issues/316#issuecomment-1416763360). Thanks, by the way.

FTR, regarding this:

> BTW, are you sure that this part is correct?

According to [this](https://github.com/findbugsproject/findbugs/blob/master/findbugs/etc/findbugsfilter.xsd#LL315C48-L315C57), multiple `Class` elements are valid, but according to [this](https://github.com/findbugsproject/findbugs/blob/master/findbugs/src/java/edu/umd/cs/findbugs/SAXBugCollectionHandler.java#L495) not (I'm not sure if the last or the first wins). So I splitted both `Class` elements into two respective `Match` elements. Thanks!

**Comment by tetebueno** [comment]
Ok, an update: code smells seem to be affected correctly by the include/exclude files... The "security hotspots" are the ones that are not being affected by these config files. Is this OK?

**Comment by gtoison** [comment]
Is the "Security Hotspot" you're referring to looking like this?
![image](https://github.com/spotbugs/sonar-findbugs/assets/86775455/3e5fa418-126a-434e-8206-239468d553b6)


The "Security Hotspot" category is populated by Sonar's native analysis, this particular one is [RSPEC-4502](https://rules.sonarsource.com/java/RSPEC-4502)
So even if SpotBugs and Sonar are coming to the same conclusion, the SpotBugs filters do not talk to the Sonar native analysis.

**Comment by tetebueno** [comment]
That's exactly how it looks.

It turned out to be as simple as adding the `SuppressWarning` annotation on top of the method:

```java
@SuppressWarning("squid:S4502") // That's the ID using the SonarQuib UID preffix.
```

Both that and the `<Match>` element in the excludes file with the `SPRING_CSRF_PROTECTION_DISABLED` pattern, takes care of the hotspot without the need to edit stuff in the Sonar GUI.

Thanks for all your help.

**Comment by gtoison** [comment]
Great, case closed 👍
