### ISSUE TITLE
new bug in old code

### ISSUE THREAD

**Issue by gecon27** [spotbugs/sonar-findbugs#320]
Configuration: SonarQube 7.7, Findbugs 3.10.0, Java profile (code on Bitbucket), New Code Period (sonar.leak.period) set to 'previous_version'. Configuration has not changed over the last months.
Problem: Analysis performed on tag v1 and then on tag v2. The latter analysis reports (since v1) a bug in a file that has NOT changed since 2018. Any thoughts/ideas why? Git diff between v1 and v2 shows clearly that the file has not changed.
If of interest, the bug reported is "Correctness - Value is null and guaranteed to be dereferenced on exception path".

**Comment by KengoTODA** [comment]
I guess that dependencies of your code have been changed (e.g. annotate method with an annotation which describes nullness of returned value).
