### ISSUE TITLE
Any release planned supporting sonarqube 8.4 ?

### ISSUE THREAD

**Issue by pethers** [spotbugs/sonar-findbugs#321]
## Issue Description
Thanks for a great tool, any release planned supporting sonarqube 8.4 ?

## Environment

| Component          | Version |
| ------------------ | ------- |
| SonarQube          | ?????   |
| Sonar-FindBugs     | ?????   |
| Maven              | ?????   |
| Gradle             | ?????   |
| Java               | ?????   |

## Code (If needed)

```java
public class BugSample1 {
  public static void hello(String message) {
       
    //Something
    Runnable r = () -> System.out.println(message);
   
    r.run();
  }
}
```

**Comment by peppe77** [comment]
we just upgraded to sonar-devedition 8.4 and also curious when there will be support for it? I understand you guys are aware of the below problem. thanks /Pedro

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.thoughtworks.xstream.core.util.Fields (file:/opt/sonarqube/data/web/deploy/plugins/findbugs/META-INF/lib/xstream-1.4.11.1.jar) to field java.lang.reflect.Proxy.h
WARNING: Please consider reporting this to the maintainers of com.thoughtworks.xstream.core.util.Fields
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by KengoTODA** [comment]
Recently I do not use SQ. Your contribution to ship new version is welcome!

We have [release procedure](https://github.com/spotbugs/sonar-findbugs/blob/d5f03306b7543584eb23fbb3c6b41aefa9696bcb/RELEASE_PROCEDURE.md) and SonarQube provides [basic guideline](https://docs.sonarqube.org/latest/extend/developing-plugin/) to release. Hope that it helps.

**Comment by pethers** [comment]
Had some problems with generate_profiles, running "groovy BuildXmlFiles.groovy" but will continue next week.

Error grabbing Grapes -- [download failed , probably missing valid  ~/.groovy/grapeConfig.xml

**Comment by KengoTODA** [comment]
#322 made necessary changes for code, and [Travis build](https://travis-ci.org/github/spotbugs/sonar-findbugs/builds/728174224) deployed artifacts to Central.
Here is PR for [SonarSource/sonar-update-center-properties](https://github.com/SonarSource/sonar-update-center-properties/pull/150). Waiting sonarsource to release.

**Comment by KengoTODA** [comment]
4.0.1 has been released, it should be available at the SonarQube Update Center.
