### ISSUE TITLE
Integrated  sonarlint eclipse plugin with sonarqube(findbugs configured). can sonarlint show findbug suggestions in eclipse in eclipse

### ISSUE THREAD

**Issue by venkatasatyanarayana** [spotbugs/sonar-findbugs#326]
## Issue Description

Hi Team,

My sonaqube is configured with findbugs
I have Integrated sonarlint eclipse plugin with sonarqube server

Can i see findbug suggestions in eclipse using sonarlint plugin. Is it possible?
If not possible. can you please suggest me eclipse alternative plugin.

Thank you very much

**Comment by gtoison** [comment]
The SpotBugs analysis can be relatively long and it does not run in SonarLint
You can use the [SpotBugs Eclipse plugin](https://spotbugs.readthedocs.io/en/latest/eclipse.html) however the rules will not synchronize with your SonarQube settings
