### ISSUE TITLE
Upgrade to 4.0.1 also upgrades Sonar-Java

### ISSUE THREAD

**Issue by mosesontheweb** [spotbugs/sonar-findbugs#327]
## Issue Description

I upgraded our production instance from 7.9.1 to 7.9.4 and also wanted to upgrade several plugins since they were already out of time. The only requirement is that I have to keep Sonar-Java lower than 6.x since some projects may still use JaCoCo binary report format. In the webgui I clicked on "Upgrade to 4.0.1" but then the button of Sonar-Java also changed to "Upgrade pending". It seems that somehow upgrading FindBugs to 4.0.1 also forces to upgrade Sonar-Java. Is this reproducable?

## Environment

| Component          | Version |
| ------------------ | ------- |
| SonarQube          | 7.9.4   |
| Sonar-FindBugs     | 3.11.1   |
| Java               | 1.8.0_25 |

**Comment by KengoTODA** [comment]
We bumped up SQ and java plugin in https://github.com/spotbugs/sonar-findbugs/commit/460dfbc2272b290f9b64fcb9823a1647b3b11e16 because old versions aren't supported by SonarSource. 

BTW sonar-java 5.13.1.18282 is the version bundled to SQ 7.9. So it's possible that version up was triggered by SQ itself.

**Comment by mosesontheweb** [comment]
Hi,

sorry for the late reply. That behaviour is really strang, I did not find any hint, that there's a dependency between FindBugs and SonarJava. That's more related to the plugin, from my point of view.

Regards, Thomas

**Comment by christopheroger** [comment]
same thing for me while upgrading from findbugs 4.0.0 to 4.0.1 on sonarqube 7.9:
sonar-java (6.3.2 build 22818) is marked as "upgrade pending"

After sonarqube restart, findbugs plugin is upgraded to 4.0.1 and sonar-java is still 6.3.2 build 22818

**Comment by gtoison** [comment]
I think that issue issue can be closed now SonarQube automatically bundles the Java plugin
