### ISSUE TITLE
Sonarqube is reporting false findbugs issues on kotlin

### ISSUE THREAD

**Issue by swatibajaj** [spotbugs/sonar-findbugs#335]
## Issue Description

I am getting redundant null check error for my code. I do not have put any null check.

dialog.setTitle(getString(R.string.please_wait))

**Style - Redundant nullcheck of value known to be non-null**
Code Smell
Info
style
Available Since
Apr 29, 2020
FindBugs (Java)
Constant/issue: 30min
This method contains a redundant check of a known non-null value against the constant null.

Again another issue that I am getting is **Performance - Method needlessly boxes a boolean constant**
val batteryLevelGood: MutableLiveData<Boolean> = MutableLiveData()
if (viewModel.batteryLevelGood.value == false){// some code}

Can anyone help with this?

## Environment

**Sonarqube version**
Developer Edition, Version 8.5 (build 37579), LGPL v3
**Rule name**: FindBugs + FB-Contrib

**Note**: My app is predominantly written in kotlin but has some files that are in JAVA

**Comment by KengoTODA** [comment]
duplicates https://github.com/spotbugs/spotbugs/issues/974
