### ISSUE TITLE
Does sonarqube 8.0 supported by this plugin? 

### ISSUE THREAD

**Issue by Saurabhj87ST** [spotbugs/sonar-findbugs#338]
## Issue Description
Does sonarqube 8.0 supported by this plugin? 
I can see in the compatibilty matrix its mentioned 7.6~ everywhere. does that mean everything supported/will work above SQ version 7.6? 
Thanks for the reply to whoever replies.

**Comment by KengoTODA** [comment]
This plugin supports LTS and later. So it should work with SQ 8.0.
