### ISSUE TITLE
The discovery JSP contains js ,XSS vulnerabilities cannot be swept

### ISSUE THREAD

**Issue by danaeliu** [spotbugs/sonar-findbugs#344]
## Issue Description

The discovery JSP contains
<script>
    window._common_counter_code_ = "channel=${param.channelId}";
    window._common_counter_uuid_ = "${param.uuid}";
</script>
XSS vulnerabilities cannot be swept

## Environment

| Component          | Version |
| ------------------ | ------- |
| SonarQube          | 8.4   |
| Sonar-FindBugs     | 4.0.3-SNAPSHOT  |
| Maven              | 3   |
| Java               | 1.6   |

## Code (If needed)

```javascript
<script>
    window._common_counter_code_ = "channel=${param.channelId}";
    window._common_counter_uuid_ = "${param.uuid}";
</script>
```

**Comment by gtoison** [comment]
Sorry for the belated answer, the project was a bit dormant and I'm now looking into the backlog of issues.
Is it still happening? If so could you please give more information because I do not understand the problem

**Comment by gtoison** [comment]
This seems to be stale issue, please reopen one if the problem persists
