### ISSUE TITLE
Jar no longer being published with Github releases

### ISSUE THREAD

**Issue by dc2tom** [spotbugs/sonar-findbugs#345]
Hi, from version 4.0.1 onwards it seems only the source code is being attached to the Github release.

Is there a reason the .jar is no longer being published?

Thanks

**Comment by KengoTODA** [comment]
We can download binary at https://repo1.maven.org/maven2/com/github/spotbugs/sonar-findbugs-plugin/

I'll automate uploading it to GitHub release in #343 .
