### ISSUE TITLE
Findbugs profiles not updated after Sonarqube plugin update

### ISSUE THREAD

**Issue by aamzerin** [spotbugs/sonar-findbugs#356]
## Issue Description

Hello,
  We are having some issues with the Following profiles : Findbugs and  Findbugs security JSP.
  It seems that after updating the sonarqube plugin (even after reinstalling the sale version), the mentioned profiles lack some rules, and donarqube says that these profiles were updated more than 1 year and 3 years ago (respectively).
  We also tried reinstalling the whole Sonarqube instance, and deleting ES indexes.
Could you help us please with this issue?
Regards,
Abdessamad 

## Environment

| Component          | Version |
| ------------------ | ------- |
| SonarQube          | 7.9.2  |
| Sonar-FindBugs     | 4.0.0 and 4.0.2   |
| Java               | 11 |

**Comment by gtoison** [comment]
Sorry for the belated answer, the project was a bit dormant and I'm now looking into the backlog of issues.
Is it still happening? If so could you please give more information (which rules are missing, server logs etc.)
