### ISSUE TITLE
False positive resolved marked issues are getting opened as new issues 

### ISSUE THREAD

**Issue by tapasgita** [spotbugs/sonar-findbugs#359]
## Issue Description

We are a running sonar build daily using Jenkins and it is observed that 
False positive resolved marked issues are getting opened as new issues after a certain interval. We use below Sonarqube environment..

##Environment :
Sonarqube,
Sonar-findbugs-3.9.2

| Component          | Version |
| ------------------ | ------- |
| SonarQube          |  7.1   |
| Sonar-FindBugs     | 3.9.2   |
| Maven              | 3.2   |
| Java               | 1.8.0.91   |

This is similar to the issue : https://community.sonarsource.com/t/old-issues-raised-as-new-issues/23461/2

Please help on this

**Comment by gtoison** [comment]
Sorry for the belated answer @tapasgita 
The plugin does not know about older issues or if they were marked as false positive, it just reports the issues found during the analysis. Then SonarQube reconciles these issues with its dabase of current issues.
So I think this is an issue with SonarQube, not with the plugin
