### ISSUE TITLE
Overlap between SpotBugs and SonarQube

### ISSUE THREAD

**Issue by amedee** [spotbugs/sonar-findbugs#362]
SonarQube has rules in the repos FindBugs and Findbugs Contrib.
SpotBugs is the spiritual successor of Findbugs.
I expect there to be overlap between SpotBugs and SonarQube.
We want to have a fast pipeline, and thus avoid and eliminate duplicate work.
What are common best practices for SpotBugs & SonarQube? Why would I still use SpotBugs if I also have a SonarQube analysis?

**Comment by gtoison** [comment]
@amedee we have just released version 4.0.5 of the plugin and rules overlapping between SpotBugs and SonarQube are now marked as deprecated.
There actually does not seem to be too many rules in that cases so you will get a better analysis breadth by using SonarQube + SpotBugs.

You're mentioning that you want a fast pipeline, have you measured how long it takes with and without SpotBugs?

**Comment by amedee** [comment]
@gtoison I no longer at that company, so I am unable to provide you with measurements.

**Comment by gtoison** [comment]
Ok, I'll close the issue then
Feel free to open a new if you try SpotBugs for your new projects!
