### ISSUE TITLE
Duplicate rule names

### ISSUE THREAD

**Issue by bonasfvck** [spotbugs/sonar-findbugs#366]
<meta name="ProgId" content="Word.Document">
<meta name="Generator" content="Microsoft Word 15">
<meta name="Originator" content="Microsoft Word 15">
<link rel="File-List" href="file:///C:/Users/DXS0UJN/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<link rel="themeData" href="file:///C:/Users/DXS0UJN/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel="colorSchemeMapping" href="file:///C:/Users/DXS0UJN/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

<p class="MsoNormal">We noticed that there are rules having duplicate names, they
have different rule keys though. Some have similar rule description, and some
don’t have. Please see sample rules below.<o:p></o:p></p>

<p class="MsoNormal"><o:p>&nbsp;</o:p></p>

Bad practice - Use of identifier that is a keyword in   later versions of Java | findbugs:NM_FUTURE_KEYWORD_USED_AS_IDENTIFIER
-- | --
Bad practice - Use of   identifier that is a keyword in later versions of Java | findbugs:NM_FUTURE_KEYWORD_USED_AS_MEMBER_IDENTIFIER
Correctness - A known null value is checked   to see if it is an instance of a type | findbugs:NP_NULL_INSTANCEOF
Correctness - A known null   value is checked to see if it is an instance of a type | findbugs:BC_NULL_INSTANCEOF
Correctness - Incompatible bit masks | findbugs:BIT_IOR
Correctness - Incompatible bit masks | findbugs:BIT_AND
Correctness - Method attempts to access a   result set field with index 0 | findbugs:SQL_BAD_RESULTSET_ACCESS
Correctness - Method attempts to access a   result set field with index 0 | findbugs:BRSA_BAD_RESULTSET_ACCESS
Correctness - Method call passes null for   non-null parameter | findbugs:NP_NULL_PARAM_DEREF_ALL_TARGETS_DANGEROUS
Correctness - Method call passes null for   non-null parameter | findbugs:NP_NULL_PARAM_DEREF
Multi-threading - Inconsistent   synchronization | findbugs:IS_INCONSISTENT_SYNC
Multi-threading - Inconsistent   synchronization | findbugs:IS2_INCONSISTENT_SYNC
Style - Method tightens nullness annotation   on parameter | findbugs:NP_METHOD_PARAMETER_TIGHTENS_ANNOTATION
Style - Method tightens nullness annotation   on parameter | findbugs:NP_METHOD_PARAMETER_RELAXING_ANNOTATION
Correctness - JUnit test method passes boolean expression   to Assert.assertFalse / Assert.assertTrue | fb-contrib:UTAO_JUNIT_ASSERTION_ODDITIES_USE_ASSERT_NOT_EQUALS
Correctness - JUnit test method passes boolean expression   to Assert.assertFalse / Assert.assertTrue | fb-contrib:UTAO_JUNIT_ASSERTION_ODDITIES_USE_ASSERT_EQUALS
Correctness - TestNG test method passes   boolean expression to Assert.assertFalse / Assert.assertTrue | fb-contrib:UTAO_TESTNG_ASSERTION_ODDITIES_USE_ASSERT_NOT_EQUALS
Correctness - TestNG test method passes   boolean expression to Assert.assertFalse / Assert.assertTrue | fb-contrib:UTAO_TESTNG_ASSERTION_ODDITIES_USE_ASSERT_EQUALS

<p class="MsoNormal"><o:p>&nbsp;</o:p></p>

<p class="MsoNormal">Are they really duplicate rules? Or they just have the same
rule names but are entirely different in the background?<o:p></o:p></p>

**Comment by bonasfvck** [comment]
Any response will be appreciated. Thanks.

**Comment by gtoison** [comment]
Hello,
I've looked into this and it looks like some (but not all) of these rules are deprecated in spotbugs.

@KengoTODA correct me if I'm wrong but currently the plugin does not mark any rules as deprecated so these rules show up in SonarQube.
If you can assign this issue to me I'll give it a try

**Comment by gtoison** [comment]
Rules that are deprecated in SpotBugs are now marked as deprecated in SonarQube if you update to 4.0.5
