### ISSUE TITLE
Support for new SonarQube LTS version 8.9?

### ISSUE THREAD

**Issue by ttoossaa** [spotbugs/sonar-findbugs#371]
Hello,

the new [SonarQube LTS version 8.9](https://www.sonarqube.org/sonarqube-8-9-lts) is not listed in the [compatibility matrix](https://github.com/spotbugs/sonar-findbugs#compatibility) of this plugin. So I would like to ask if the current findbugs plugin is compatible with it?

Thanks a lot.

**Comment by janosvitok** [comment]
Sonar [documentation](https://docs.sonarqube.org/latest/instance-administration/plugin-version-matrix/) (or directly the [table](https://update.sonarsource.org/plugins/compatibility-matrix.html)) Lists 4.0.3 as compatible with 8.9 LTS and none compatible with 9.0. We currently run 8.9.0 LTS with 4.0.3 FindBugs plugin and it works fine.

Support for 9.0 is in the works, see #368.

**Comment by ttoossaa** [comment]
Cool. Thanks a lot.
