### ISSUE TITLE
Could not be matched to its original source file. It might be a dynamically generated class.

### ISSUE THREAD

**Issue by rambhawan** [spotbugs/sonar-findbugs#372]
## Issue Description

Integrated Sonar.
and getting logs below.
ource file. It might be a dynamically generated class.
The class '.VersionView' could not be matched to its original source file. It might be a dynamically generated class.

## Environment

| Component          | Version |
| ------------------ | ------- |
| SonarQube          | 2.7.0   |
| Sonar-FindBugs     |    |
| Maven              | ?????   |
| Gradle             | 7.0   |
| Java               | 10.0   |

## Code (If needed)

```java
public class BugSample1 {
  public static void hello(String message) {
       
    //Something
    Runnable r = () -> System.out.println(message);
   
    r.run();
  }
}
```

**Comment by KengoTODA** [comment]
The code you shared contains nothing about the `VersionView` class. Do you have any idea where the class comes from?

**Comment by gtoison** [comment]
I'm closing this issue as there isn't enough information to understand what might be the problem.
Please feel free to reopen an new issue if needed.
