### ISSUE TITLE
Kotlin support missing

### ISSUE THREAD

**Issue by BenjaDiaz** [spotbugs/sonar-findbugs#373]
## Issue Description

Spotbugs allows for bytecode analysis, which can be used for Kotlin projects. The sonar plugin does not support Kotlin, so for now we create a 'fake' Java file inside the project to trigger the analysis.

Is there anything else needed to support this usecase besides adding Kotlin in the JVM support languages here?

https://github.com/spotbugs/sonar-findbugs/blob/master/src/main/java/org/sonar/plugins/findbugs/FindbugsPlugin.java#L38

Thanks in advance!

**Comment by KengoTODA** [comment]
refs https://github.com/spotbugs/spotbugs/issues/573

Kotlin support itself isn't enough at this moment.

**Comment by KengoTODA** [comment]
duplicates https://github.com/spotbugs/spotbugs/issues/974
