### ISSUE TITLE
When will sporbugs version 4.4.0 be supported?

### ISSUE THREAD

**Issue by jooeji** [spotbugs/sonar-findbugs#376]
When the plugin will sporbugs version 4.4.0 be supported?

**Comment by KengoTODA** [comment]
Submit a PR to make it real by yourself :+1:! Currently this repo lacks manpower and waits for contribution severely.
I hope that 9ff7075b9a155a3a2340149e6153a65a0de52f00 helps you to understand which kind of changes are necessary.
