### ISSUE TITLE
Is there a way to ignore Spotbugs' annotation in SonarQube?

### ISSUE THREAD

**Issue by go2master** [spotbugs/sonar-findbugs#390]
## Issue Description

I use SpotBugs in IDEA, and FindBugs in SonarQube. I suppress SpotBugs' warnings with FindBugs' annotations. SonarQube will recognize the annotations and ignore the warnings.

I want SonarQube not to ignore the warnings suppressed with annotations in IDEA.

**Comment by gtoison** [comment]
Hello, I'm not sure if that's possible but there seem to be a system property for ignoring annotations in Spotbugs:
https://github.com/findbugsproject/findbugs/blob/451c28097c22ef8e6f8943e5ebe6a16ff41beff7/findbugs/src/java/edu/umd/cs/findbugs/ba/AnnotationDatabase.java#L51

So you could experiment setting the `findbugs.ignoreBuiltinAnnotations` system property to false during the analysis.

You will probably get a better answer asking in the spotbugs project, all the spotbugs experts are there!

**Comment by go2master** [comment]
> 
> So you could experiment setting the `findbugs.ignoreBuiltinAnnotations` system property to false during the analysis.
> 
> You will probably get a better answer asking in the spotbugs project, all the spotbugs experts are there!

I tried to set the property=false then true, both not work.
My settings are SonarQube6.7.7-community Docker Image、sonar-findbugs-plugin-3.9.3、sonar-java-plugin-5.2.0.13398. The command is 'java -jar lib/sonar-application-6.7.7.jar -Dsonar.log.console=true -D**findbugs.ignoreBuiltinAnnotations**=false -Dsonar.jdbc.username=sonar -Dsonar.jdbc.password=sonar -Dsonar.jdbc.url= -Dsonar.web.javaAdditionalOpts= -Djava.security.egd=file:/dev/./urandom'
Thank you. 
There must be a way to ignore the annotations. But I have not find the code.
