### ISSUE TITLE
Findbugs plugin does not support JDK 17

### ISSUE THREAD

**Issue by farcop** [spotbugs/sonar-findbugs#394]
## Issue Description

The following errors occurred during analysis:
  Error scanning com/ucp/auth/UcpAuthApplication for referenced classes
    java.lang.IllegalArgumentException: Unsupported class file major version 61
      At org.objectweb.asm.ClassReader.<init>(ClassReader.java:189)
      At org.objectweb.asm.ClassReader.<init>(ClassReader.java:170)
      At org.objectweb.asm.ClassReader.<init>(ClassReader.java:156)
      At edu.umd.cs.findbugs.asm.FBClassReader.<init>(FBClassReader.java:35)
      At edu.umd.cs.findbugs.classfile.engine.asm.ClassReaderAnalysisEngine.analyze(ClassReaderAnalysisEngine.java:48)
      At edu.umd.cs.findbugs.classfile.engine.asm.ClassReaderAnalysisEngine.analyze(ClassReaderAnalysisEngine.java:34)
      At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:261)
      At edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:75)
      At edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:38)
      At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:261)
      At edu.umd.cs.findbugs.FindBugs2.buildReferencedClassSet(FindBugs2.java:806)
      At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:249)
      At org.sonar.plugins.findbugs.FindbugsExecutor$FindbugsTask.call(FindbugsExecutor.java:235)
      At java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
      At java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
      At java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
      At java.base/java.lang.Thread.run(Thread.java:833)

## Environment

| Component          | Version |
| ------------------ | ------- |
| SonarQube          | 8.9 (build 43852)   |
| Sonar-FindBugs     | 4.0.3   |
| Maven              | 3.8.3   |
| Java               |  openjdk:17-jdk  |

**Comment by farcop** [comment]
Can not reproduce in 4.0.4

**Comment by pradeepkottalage** [comment]
Same error i m also getting can somebody confirm RCA

**Comment by gtoison** [comment]
@pradeepkottalage you're most likely running an old version of the plugin that wasn't compatible with newer versions of Java: you need to upgrade the plugin
