### ISSUE TITLE
We have an issue that the execution of Sonarqube Scan which fails during the package-branch job with error on Concourse

### ISSUE THREAD

**Issue by bolboaca** [spotbugs/sonar-findbugs#434]
## Issue Description

Dear colleagues, 

we have an issue that the execution of Sonarqube Scan which fails during the package-branch job with error on Concourse. 

https://ci-plmv5.pre.shs.eu.dp.odp.cloud.vwgroup.com/teams/build-mbb/pipelines/BM-mbbb-86040-rlu-msg/jobs/package-branch-plumber/builds/18
java.lang.IllegalStateException: Can not execute Findbugs
Caused by: java.io.FileNotFoundException: /source/rlu/target/surefire-reports (Is a directory)

 

I was wondering why this step 'Reusing the report' is executed:
INFO: Loading findbugs plugin: /source/.scannerwork/findbugs/findsecbugs-plugin.jar
INFO: Findbugs output report: /source/.scannerwork/findbugs-result.xml
INFO: FindBugs report is already generated /source/rlu/target/surefire-reports. Reusing the report.

We have another service, which are most similar and have the same sonar configs, there the 'reusing the report' step is not executed and sonarqubeScan is successfull (https://ci-plmv5.pre.shs.eu.dp.odp.cloud.vwgroup.com/teams/build-mbb/pipelines/BM-mbbb-86039-rs-msg/jobs/package-branch-plumber/builds/39)

Is this an configuration issue?

Can you please support here to solve the issue so that the SonarqubeScan runs successfull. 

With the new rules as long as this SonarqubeScan failes we cannot deploy..

Attached is the sonar-project.properties which is used for RLU. Same (with adapted paths) is also used for RS. Please let me known if you need anything else.

For other services with the same configuration the sonar scan works.

Thank you!

sonar.language=java
sonar.java.coveragePlugin=jacoco
# specifies all the src files which should be checked (for bugs and for codecoverage). Here you exclude the test sources to exclude them from code coverage calculation
sonar.sources=rlu/src/main/java
# specifies all the jacoco reports in the module, if the module has submodules
sonar.coverage.jacoco.xmlReportPaths=rlu/target/site/jacoco/jacoco.xml

## Environment

Java, Version 8.9.5 (build 50698)LGPL v3

| Component          | Version |
| ------------------ | ------- |
| SonarQube          | ?????   |
| Sonar-FindBugs     | ?????   |
| Maven              | ?????   |
| Gradle             | ?????   |
| Java               | ?????   |

## Code (If needed)

```java
public class BugSample1 {
  public static void hello(String message) {
       
    //Something
    Runnable r = () -> System.out.println(message);
   
    r.run();
  }
}
```

**Comment by gtoison** [comment]
Could you please provide the relevant parts of the logs and configuration? The links you provided are for your internal build system.

I suspect that you're setting `sonar.findbugs.reportpaths` with a file that is actually a folder

**Comment by bolboaca** [comment]
[20211207_RLU_Sonar.txt](https://github.com/spotbugs/sonar-findbugs/files/7806126/20211207_RLU_Sonar.txt)
Hopefully this helps.

**Comment by gtoison** [comment]
Can you check the value of the `sonar.findbugs.reportpaths` property? It might be set on your SonarQube server:

![image](https://user-images.githubusercontent.com/86775455/148035446-4b4ef4c3-241f-4b65-b524-cb1aa6be9f8f.png)

**Comment by gtoison** [comment]
Version 4.0.6 of the plugin was just released and it included a fix to ignore directories in the report paths (empty files were already ignored)
