### ISSUE TITLE
A couple of questions about sonar-update-center-action

### ISSUE THREAD

**Issue by gtoison** [spotbugs/sonar-findbugs#528]
Hello @KengoTODA 

Sorry to bother you but I have questions about sonar-update-center-action and I'm not familiar with typescript or Github actions.

The Pull Requests in https://github.com/SonarSource/sonar-update-center-properties are in the Draft status. I tried to fix that with this commit https://github.com/spotbugs/sonar-findbugs/commit/e98a72b2ac49f1ab4152e9dad9ed09bacb6627f8 but I does not seem better. Now I think that the action uses the compiled `.js` script from the `dist` folder, so I suppose that I have to compile the typescript code and push the resulting .js file(s), right?
I tried to do that in https://github.com/spotbugs/sonar-findbugs/pull/524 and it would be great if you could have a quick look at it. I ran the `npm run all` command to compile and I was surprised that it changed the index.js substantially.
.
Can you please close https://github.com/SonarSource/sonar-update-center-properties/pull/291 (there was an unrelated blocking problem in that version, it should not be released) and mark https://github.com/SonarSource/sonar-update-center-properties/pull/293 as ready for review?

The [post](https://community.sonarsource.com/t/new-release-sonar-findbugs-plugin-4-1-3/61969) on the Sonarsource forum is not formatted properly, I looked at the code and did not see anything obviously wrong. Any idea what might be the problem?

There also seem to be an issue with the way the URL for the Sonarcloud analysis is encoded, it should be:
`https://sonarcloud.io/summary/new_code?id=com.github.spotbugs%3Asonar-findbugs-plugin`
but comes out as:
`https://sonarcloud.io/summary/new_code?id=com.github.spotbugs%253Asonar-findbugs-plugin`
in the forum post.

 Sorry for the beginner questions, any pointers would be appreciated as I'm not even sure what tools/IDE would be recommended (I'm on Windows)

Thanks in advance

**Comment by KengoTODA** [comment]
Hello, sorry I didn't notice this issue before. 
You've closed this issue but please tell me if any blockers remain.

**Comment by gtoison** [comment]
No problem, I figured you were busy and did not want to bother you too much
I _think_ I've figured out these problems, we'll see how it goes next time.

Can you please go to https://github.com/SonarSource/sonar-update-center-properties/pulls and close the two outstanding pull requests?

**Comment by KengoTODA** [comment]
closed, thanks!
