### ISSUE TITLE
Nested configuration

### ISSUE THREAD

**Issue by BlackAngelTiger** [spotbugs/sonar-findbugs#54]
Hi,

we have the proplem that the findbugs build scanes our libraries we are using to build the projects, but it although tries to scan the transitive libraries.
Because of the fact that we only wont to have issues, which we can handle and correct, we want that findbugs only scanse the sources we are providing to Sonar as sources or binareies. To do so we want to set the "nested" configuration to false.

> -nested[:true|false]
> This option enables or disables scanning of nested jar and zip files found in the list of files and directories to be analyzed. By default, scanning of nested jar/zip files is enabled. To disable it, add -nested:false to the command line arguments. 
> Sources: http://findbugs.sourceforge.net/manual/running.html#d0e503 (nearly at the end of the page)

Is it possible to make this configuration in Sonar so that the findbugs plug-In path this through?

Best Regards

**Comment by h3xstream** [comment]
I did not know about this option. It may trigger bunch of warnings related to class not found.

For example: If you have a servlet MyServlet is extending HttpServlet. In order confirm that the class is extending HttpServlet loading this external class might be needed.

**Comment by BlackAngelTiger** [comment]
@h3xstream Yes, but you do this currently as well if the classes aren't there.

**Comment by h3xstream** [comment]
@BlackAngelTiger You can now configure FindBugs/SpotBugs with the Maven plugin and the Sonar task will pickup the result. Make you use the same profile with Maven. https://github.com/SonarQubeCommunity/sonar-findbugs/releases/tag/3.6.0

**Comment by BlackAngelTiger** [comment]
@h3xstream Thank you, but we need to use gradle for the build.

**Comment by h3xstream** [comment]
Just for Ref:
Sonar-FindBugs doesn't plan to offer all the option of SpotBugs in the Sonar UI. It is much more effective to allow the configuration from the build tool and pickup the report in Sonar. This simplify the architecture of the plugin on the long term.
