### ISSUE TITLE
Is  sonar-findbugs plugin compatible with Sonarqube EE 9.4?

### ISSUE THREAD

**Issue by shafemoh** [spotbugs/sonar-findbugs#576]
Hi team,
we are currently hosting Sonarqube EE 9.2.4 and we will be upgrading to Sonarqube 9.4.0. We are currently using [sonar-findbugs-plugin-4.0.5.jar](https://github.com/spotbugs/sonar-findbugs/releases/download/4.0.5/sonar-findbugs-plugin-4.0.5.jar).
Should we upgrade the sonar-findbugs plugin to some higher version (if so, to which version ? )
OR Can we stay on [sonar-findbugs-plugin-4.0.5.jar](https://github.com/spotbugs/sonar-findbugs/releases/download/4.0.5/sonar-findbugs-plugin-4.0.5.jar) ?

Regards @shafemoh

**Comment by gtoison** [comment]
Hello, you should be able to stay on 4.0.5 however this version is quite old at this point and the recent releases have introduced a couple of fixes and enhancements.
In particular you'll get a newer version of SpotBugs and Scala support
You can upgrade to [4.1.6](https://github.com/spotbugs/sonar-findbugs/releases/tag/4.1.6)

**Comment by shafemoh** [comment]
Hi @gtoison Do you have any compatibility matrix for this plugin?

**Comment by gtoison** [comment]
There's one [here](https://github.com/spotbugs/sonar-findbugs), or you had something else in mind?

**Comment by shafemoh** [comment]
![image](https://user-images.githubusercontent.com/96038516/173060370-97e7aa0b-caf0-43c7-90f5-a5130866cb16.png)

Thanks for the compatibility matrix.. What does 7.9~ mean? Does it mean 7.9 and higher?

**Comment by gtoison** [comment]
Yes, 7.9~ means 7.9 and higher
