### ISSUE TITLE
Findbugs Security JSP - failing execution

### ISSUE THREAD

**Issue by csrvsk** [spotbugs/sonar-findbugs#603]
Must-share information (formatted with [Markdown](https://commonmark.org/help/)):

which versions are you using (SonarQube, Scanner, Plugin, and any relevant extension)
SonarQube 9.3 & 9.5 (2 versions), Scanner 4.7,
what are you trying to achieve
Trying to run scan on project containing JSP, Java, JS, xml
what have you tried so far to achieve this
10:51:38.412 DEBUG: category EXPERIMENTAL details → Experimental and not fully vetted bug patterns
10:51:39.682 WARN: JSP files were found in the current (sub)project (C:\JAVA\APPLICATIONS\DM\Issue) but FindBugs requires their precompiled form. For more information on how to configure JSP precompilation : [JSP precompilation · find-sec-bugs/find-sec-bugs Wiki · GitHub](https://github.com/find-sec-bugs/find-sec-bugs/wiki/JSP-precompilation)
10:51:39.687 WARN: Findbugs needs sources to be compiled. Please build project before executing sonar or check the location of compiled classes to make it possible for Findbugs to analyse your (sub)project (C:\JAVA\APPLICATIONS\DM\Issue).
10:51:39.712 INFO: Findbugs analysis skipped for this project.
Execution Succeeded with SonarQube Version 9.3

But with Sonar Version 9.5

10:57:54.594 DEBUG: category EXPERIMENTAL details → Experimental and not fully vetted bug patterns
10:57:55.942 WARN: JSP files were found in the current (sub)project (C:\JAVA\APPLICATIONS\DM\Issue) but FindBugs requires their precompiled form. For more information on how to configure JSP precompilation : [JSP precompilation · find-sec-bugs/find-sec-bugs Wiki · GitHub](https://github.com/find-sec-bugs/find-sec-bugs/wiki/JSP-precompilation)
10:57:55.950 WARN: Findbugs needs sources to be compiled. Please build project before executing sonar or check the location of compiled classes to make it possible for Findbugs to analyse your (sub)project (C:\JAVA\APPLICATIONS\DM\Issue).
10:57:55.967 DEBUG: eslint-bridge server will shutdown
10:58:08.513 INFO: ------------------------------------------------------------------------
10:58:08.514 INFO: EXECUTION FAILURE
10:58:08.514 INFO: ------------------------------------------------------------------------
10:58:08.515 INFO: Total time: 2:21.076s
10:58:08.716 INFO: Final Memory: 84M/287M
10:58:08.717 INFO: ------------------------------------------------------------------------
10:58:08.718 ERROR: Error during SonarScanner execution
java.lang.IllegalStateException: Can not execute Findbugs

Please let me know how to fix it in the latest version 9.5
and also how to fix "eslint-bridge server will shutdown

Thanks
Shiva

**Comment by gtoison** [comment]
I will close this as there does not seem to be further questions, please don't hesitate to create a new issue
