### ISSUE TITLE
"Can't find ClassInfo" when looking at dependency

### ISSUE THREAD

**Issue by turturel** [spotbugs/sonar-findbugs#630]
## Issue Description
We have a Maven project which produces a war and has Liquibase as a dependency.

After updating to Liquibase 4.9.1 from an older version Sonar scans started failing with: **_Caused by: java.util.concurrent.ExecutionException: java.lang.AssertionError: Can't find ClassInfo for liquibase\package-info_**

I tried various exclusion patterns but nothing works unless I exclude the actual classes that use Liquibase.

What doesn't SpotBugs like about liquibase-core-4.9.1.jar\liquibase\package-info.class?

Attached partial debug log. [log.txt](https://github.com/spotbugs/sonar-findbugs/files/9363185/log.txt)

Thanks!

## Environment
SonarQube 8.9.9
Sonar-FindBugs 4.2.0
Maven 3.8.4
Java 1.8.0_321

**Comment by gtoison** [comment]
This looks like an error in SpotBugs itself, not in the Sonar plugin.
The exception here seems to rethrown without keeping track of the initial problem so I'm not sure what might be happening:
https://github.com/spotbugs/spotbugs/blob/6b8f2d08708f2144badece3778705aa4121672c5/spotbugs/src/main/java/edu/umd/cs/findbugs/visitclass/PreorderVisitor.java#L422

It would be great if you could share a small project reproducing the issue, using SpotBugs directly to remove the plugin from the equation

**Comment by turturel** [comment]
@gtoison thank you for looking into this.

I created a very small Maven project and I was able to reproduce the issue using both SpotBugs GUI as well as the spotbugs-maven-plugin.

Should I open an issue against spotbugs/spotbugs or continue with this one?

**Comment by gtoison** [comment]
Yes, better open an issue with spotbugs
Bonus points if you can share the small project reproducing the issue!

**Comment by turturel** [comment]
Opened issue with spotbugs (and included the small project I used to reproduce the issue).

Thank you for your help.
