### ISSUE TITLE
Can not execute Findbugs: One (sub)project contains Java source files that are not compiled

### ISSUE THREAD

**Issue by dkeitzel** [spotbugs/sonar-findbugs#640]
## Issue Description

This is most likley an addendum to #559, but we're still affected with version 4.2.0. The verified last "known good" version was 4.0.6.

```
13:19:54  [ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.9.1.2184:sonar (default-cli) on project sonar: Can not execute Findbugs: One (sub)project contains Java source files that are not compiled (/home/containeruser/build/workspace/demo_sonar8_PR-11/modules/webapp).
13:19:54  [ERROR] Property sonar.java.binaries was not set, it is required to locate the compiled .class files. For instance set the property to: sonar.java.binaries=target/classes
13:19:54  [ERROR] Sonar JavaResourceLocator.classFilesToAnalyze was empty
```

Command line: `mvn -Dsonar.login=****** -Dsonar.branch.name=sqtest/feature org.sonarsource.scanner.maven:sonar-maven-plugin:3.9.1.2184:sonar`

Some things to know:
- This is a multi module project
- There is a `mvn clean verify` run with a JaCoCo agent before the SonarQube analysis.
- That `mvn clean verify` run uses Java 8

I'm happy to provide more information and/or a sample project.

## Environment

| Component          | Version |
| ------------------ | ------- |
| SonarQube          | 8.9.9 |
| Sonar-FindBugs     | 4.2.0   |
| Maven              | 3.6.3 |
| Java               | 11.0.16 |

**Comment by gtoison** [comment]
Yes, it would be great if you could share a sample project.
Based on your logs (`Property sonar.java.binaries was not set` and `Sonar JavaResourceLocator.classFilesToAnalyze was empty`) it looks like there are indeed no `.class` files sent to the plugin. Or at least there's no way for the plugin to locate them.

I see that the module is named "webapp", does it contain java or JSP sources and are they compiled to .class files?

**Comment by dkeitzel** [comment]
> I see that the module is named "webapp", does it contain java or JSP sources and are they compiled to .class files?

Spot on. The module "webapp" only contains a JSP source file (and a web.xml), but no java and no resulting class files. Removing that module resolves the error.

> Yes, it would be great if you could share a sample project.
I'll prepare it.

**Comment by gtoison** [comment]
When you have JSP sources you need either to compile them to .class file or to set the `sonar.findbugs.allowuncompilecode` to true

**Comment by gtoison** [comment]
There are sample projects illustrating how to pre compile JSP source:

https://github.com/spotbugs/sonar-findbugs/tree/master/src/test/resources/projects/jspc-jetty
https://github.com/spotbugs/sonar-findbugs/tree/master/src/test/resources/projects/jspc-sling

**Comment by dkeitzel** [comment]
I see. It actually does work with `-Dsonar.findbugs.allowuncompiledcode=true`. However, with 4.0.6. it was working without enabling that switch.

Thank you nonetheless! This is good enough for me 👍 

For completeness, the sample project: https://github.com/dkeitzel/sonar

**Comment by gtoison** [comment]
Cheers, beware that setting `sonar.findbugs.allowuncompiledcode=true` might mask issues in other module so you should be able to set it only for the module that is not compiled
The purpose of this error is to alert the error that SpotBugs can't analyse the project because it cannot find the `.class` files

Out of curiosity, why don't you pre compile the JSP sources?

**Comment by dkeitzel** [comment]
Got it, fair point.

> Out of curiosity, why don't you pre compile the JSP sources?

This is just an internal sample project to show the integration of SonarQube with Maven, Jenkins and Bitbucket. It is also being used to test for regressions when upgrading one of those services. That regression test failed the other day when updating SonarQube and a bunch of plugins.

Real projects would either precompile JSPs or would be mindful about using `allowuncompiledcode=true`. I hope 😅

**Comment by gtoison** [comment]
Understood, thanks for explaining
In case that helps here's a way to set the flag at module level:

Maven: https://github.com/spotbugs/sonar-findbugs/blob/master/src/test/resources/projects/multi-module/multi-module-jsp-uncompiled/pom.xml
Gradle: https://github.com/spotbugs/sonar-findbugs/blob/master/src/test/resources/projects/multi-module/multi-module-jsp-uncompiled/build.gradle

**Comment by dkeitzel** [comment]
Thank you, I'll set the flag at module level.
