### ISSUE TITLE
Is sonar-findbugs compatible with Sonarqube 10.x

### ISSUE THREAD

**Issue by ericrichtert** [spotbugs/sonar-findbugs#724]
Sonar version: 9.9
findbugs sonar plugin version: latest

We want to upgrade to SQ 10.0, is sonar-findbugs compatible with this version?

**Comment by gtoison** [comment]
I've added SQ 10 to the integration tests and it seems to work just fine. See https://github.com/spotbugs/sonar-findbugs/pull/725
The integration tests run the builds of some sample project and then check that the issues are reported in SonarQube.

I've just had to make some changes that only relate to the mocking of loggers for unit tests, that does not matter for the production code.

**Comment by gtoison** [comment]
Hello @reitzmichnicht 
I hope it's OK to ping you here since I saw your message in the SonarQube [release annoucement](https://community.sonarsource.com/t/sonarqube-10-0-released/88544)
Could it be that the plugins need to be installed again? Anything interesting in the logs?

**Comment by reitzmichnicht** [comment]
We always build a fresh docker image, but it looks like that the plugins are not recognized anymore. I have to check the reason, maybe filesystem permissions issue.

**Comment by reitzmichnicht** [comment]
> Hello @reitzmichnicht I hope it's OK to ping you here since I saw your message in the SonarQube [release annoucement](https://community.sonarsource.com/t/sonarqube-10-0-released/88544) Could it be that the plugins need to be installed again? Anything interesting in the logs?

Except that the findbugs quality profiles are duplicated now (the new ones have the built-in badge) its working now since I fixed a small typo so that they are copied to the correct directory again.

**Comment by gtoison** [comment]
Thanks, so we can say that the plugin works with SonarQube 10!

**Comment by reitzmichnicht** [comment]
I have to revert my statement. Looks like that some (all?) findbug rules are now applied to main code AND test code. At least thats what we see. We have lots of new findings related to test code where those rules seem to be not applicable before.

**Comment by gtoison** [comment]
The analysis of tests is actually a feature and was added in https://github.com/spotbugs/sonar-findbugs/pull/706 
It only activates when running with SonarQube >= 9.8 

I've added an option to exclude tests from the anlysis in #720 but it is not released at this point.

Does it make sense and do you need a release with that new option to disable the analysis of tests?

**Comment by gtoison** [comment]
Good point: the release note had the corresponding PR but it was not clear at all
Remark added!
