### ISSUE TITLE
sonarqube displays errors from a profile that is not assigned to the project

### ISSUE THREAD

**Issue by mos9mu** [spotbugs/sonar-findbugs#727]
Hi team,
could you please help us why sonar displays errors from a profile that is not assigned to the project:

A rule from FindBugs(Java) is displayed, but this project is assigned to Scala profile.
<img width="917" alt="error" src="https://github.com/spotbugs/sonar-findbugs/assets/117162895/b0971f69-3cf5-411f-a699-d906b6bbd981">

<img width="413" alt="project" src="https://github.com/spotbugs/sonar-findbugs/assets/117162895/209a8ba5-450c-4ce3-a8c3-51f5897f1524">

**Comment by gtoison** [comment]
Hello,
I had a similar question a while ago and the answer from Julien at SonarSource was:

> The language of rules has no strong relation with language of files. Most Sensors will report issues for rule of language X only on files of language X, but this is not enforced by the platform. For example, our Java analyzer could detect issues in Spring framework configuration files. Those rules used to be classified as Java rules, but the configuration file is an XML file.
> 
> Consequently, quality profiles are not dynamically computed based on the project files. A project will have an active quality profile for all languages on the server.
> 
> The Findbugs Sensor already declares the list of file languages it supports:
> It means that every time the project contains at least one file for one of the languages Java, Jsp, scala, or clojure, the Sensor will run (you will see its name in the logs).
https://community.sonarsource.com/t/activerule-and-project-quality-profile/54412/2?u=gtoison

So my guess is that the rule is part of your default Java profile. 
The project does not have a Java profile therefore it uses it and the default Java profile, including that rule

**Comment by gtoison** [comment]
I'll close this issue since there does not seem to be further questions
