### ISSUE TITLE
FindBug Rules are triggered for Quality PRofile Kotlin and XML

### ISSUE THREAD

**Issue by Malgosiatobiasz1** [spotbugs/sonar-findbugs#729]
We are having some issues with Sonarqube analysis for an Android application in Kotlin: 
although the project Quality Profile is only detecting Kotlin (detekt all) and XML (Sonar way), some FindBugs rules are being triggered. Can you help us understand why FindBugs rules are used for a Kotlin project and how can we disable those for our projects’ analysis?
We rechecked the Quality Profiles used in the project and it does not contain FindBug Rule

**Comment by gtoison** [comment]
I suspect that these rules are in your default java profile, even though your project is not java, Sonarqube will pick a profile for every single language. In case you did not set a profile for that language, it will select the default one.
The rules are enabled so the Spotbugs sensor runs and it analyses your code (your compiled .class files actually).
This is really not obvious but that's the way Sonarqube works, here's the answer that helped me figuring this out:
https://community.sonarsource.com/t/activerule-and-project-quality-profile/54412/2

**Comment by gtoison** [comment]
I'll close this issue since there does not seem to be further questions
