### ISSUE TITLE
SonarQube fails with Java 17

### ISSUE THREAD

**Issue by HlebMaliborski** [spotbugs/sonar-findbugs#731]
SonarQube Version : 9.9.1
JDK : 17
gradle: 8.1.1
sonarqube-gradle-plugin: 4.3.1.3277
Android studio : 2022.3.1 Patch 1

Hello, I try to use sonarqube with java 17 but get error:
`Couldn't get class info for java/util/Set
    java.lang.IllegalArgumentException: Unsupported class file major version 61
      At org.objectweb.asm.ClassReader.<init>(ClassReader.java:184)
      At org.objectweb.asm.ClassReader.<init>(ClassReader.java:166)
      At org.objectweb.asm.ClassReader.<init>(ClassReader.java:152)
      At edu.umd.cs.findbugs.asm.FBClassReader.<init>(FBClassReader.java:35)
      At edu.umd.cs.findbugs.classfile.engine.asm.ClassReaderAnalysisEngine.analyze(ClassReaderAnalysisEngine.java:48)
      At edu.umd.cs.findbugs.classfile.engine.asm.ClassReaderAnalysisEngine.analyze(ClassReaderAnalysisEngine.java:34)
      At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:262)
      At edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:75)
      At edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:38)
      At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:262)
      At edu.umd.cs.findbugs.ba.XFactory.getXClass(XFactory.java:687)
      At edu.umd.cs.findbugs.ba.AnalysisContext.setAppClassList(AnalysisContext.java:975)
      At edu.umd.cs.findbugs.FindBugs2.setAppClassList(FindBugs2.java:877)
      At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:223)
      At org.sonar.plugins.findbugs.FindbugsExecutor$FindbugsTask.call(FindbugsExecutor.java:235)
      At java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
      At java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
      At java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
      At java.base/java.lang.Thread.run(Thread.java:833)`

Could you please help there?

**Comment by gtoison** [comment]
Hello, what version of the sonar-findbugs do you have installed on the server?
The recent/latest versions should be able to process java 17 class files.

**Comment by HlebMaliborski** [comment]
@gtoison hi, sorry for delay. I checked, we have latest version installed, but still same problems.

**Comment by gtoison** [comment]
That's very strange (I am also using the plugin with JDK 17).
Can you please check you build logs and confirm that you see something like:

```
[INFO] Sensor FindBugs Sensor [findbugs]
[INFO] Findbugs plugin version: 4.2.3
[INFO] Loading findbugs plugin: ...
```

**Comment by HlebMaliborski** [comment]
I have this information
`09:38:00  Sensor FindBugs Sensor [findbugs]
09:38:01  Loading findbugs plugin: /home/jenkins/.../findbugs/fb-contrib.jar
09:38:02  Loading findbugs plugin: /home/jenkins/.../findbugs/findsecbugs-plugin.jar
09:38:02  Findbugs output report: /home/jenkins/.../findbugs-result.xml`

**Comment by gtoison** [comment]
The `[INFO] Findbugs plugin version: x.y.z` log message was added in #599 and released in version 4.2.2 so I think the version of the plugin actually running in your build is not 4.2.3

Maybe you're connecting to another SonarQube server? Normally when the build is running the sonar plugin downloads the plugins from the server and then runs them.

**Comment by gtoison** [comment]
Any additional information or questions?
In the meantime I have released version 4.2.4 and this adds support to code compiled with JDK 21

**Comment by HlebMaliborski** [comment]
@gtoison no, thanks for the help!

**Comment by gtoison** [comment]
Thanks, so (unless I misunderstood) I'll close this as resolved
