### ISSUE TITLE
Spike in SonarQube Findings

### ISSUE THREAD

**Issue by mahalekiran** [spotbugs/sonar-findbugs#732]
## Environment

| Component          | Version |
| ------------------ | ------- |
| SonarQube          | 10.0  |
| Sonar-FindBugs     |4.2.3   |

There was upgrade of sonar from 9.9 to 10, and as part of this upgrade the findbugs plugin was updated from 4.2.2 to 4.2.3.
In one of the project, we had a pull-request with no code changes. The PR quality check was successful, but on master it failed.
suddenly 30 new bugs and many code smells were reported.
Interestingly, the creation date is way in the past, and also the rules are not new or updated.

**Comment by gtoison** [comment]
The analysis of `.class` files corresponding to unit tests was added in [4.23](https://github.com/spotbugs/sonar-findbugs/releases/tag/4.2.3)
My best guess is that the new findings are in your tests

**Comment by gtoison** [comment]
I will close  this soon because there does not seem to be further questions or updates.
Please do not hesitate to open a new issue if needed
