### ISSUE TITLE
new option to analyze tests

### ISSUE THREAD

**Issue by eshwarkarthikn** [spotbugs/sonar-findbugs#804]
Hi,

We have upgraded our Production SonarQube application to v9.9LTS from v8.9 LTS very recently. As part of the upgrade, we have also updated the sonar-findbugs plugin to v4.2.3. Now, we have few complaints from users that their tests are being analyzed which they don't want to. We found that these vulnerabilities are coming up from findbugs plugin rules. While going through the release notes, we came to know Tests are analyzed by default in v4.2.3 and provided an option to disable this in v4.2.4.

Considering production environment and upcoming release cycles, We need to check with you and confirm if there will be any further issues that we may expect if we upgrade to v4.2.4.

Thank you.
@gtoison

**Comment by gtoison** [comment]
Hello, there are no new issue I am aware of with 4.2.4
As you have noted it adds the option to disable the analysis of tests.

Please note that the upcoming next version will most probably upgrade SpotBugs from 4.7.3 to 4.8.0 so there should be new rules and some fixes to the underlying code analysis.

**Comment by gtoison** [comment]
I will close this soon since there does not seem to be further questions
