### ISSUE TITLE
bugs in findbugs-result.xml but not in Sonarqube

### ISSUE THREAD

**Issue by the-player777** [spotbugs/sonar-findbugs#83]
Hello,

This issue is similar to this one: https://github.com/SonarQubeCommunity/sonar-findbugs/issues/66

But the difference is that I'm running it with Jenkins (sonar-scanner 2.8). The findbugs-result.xml is generated and uploaded. I have some warning in my logs but nothing related to findbugs itself. Maybe I missed something on the configuration? Note that findbugs was working before we decided to upgrade sonar (5.1 to 6)

Here is my configuration in Jenkins (Maven project):
```
sonar.projectKey=sonar:my-project
sonar.projectName=my-project
sonar.projectVersion=${POM_VERSION}
sonar.sources=myproject/sources
sonar.java.binaries=**/target/classes
sonar.sourceEncoding=UTF-8
sonar.language=java
```

Thanks in advance for your help

**Comment by h3xstream** [comment]
Which Quality profile was activated?
