### ISSUE TITLE
Update PAT_TO_FORK

### ISSUE THREAD

**Issue by KengoTODA** [spotbugs/sonar-findbugs#869]
## Issue Description

[This PR for SonarSource/sonar-update-center-properties](https://github.com/SonarSource/sonar-update-center-properties/pull/461) was created automatically, based on the `PAT_TO_FORK` security token made by me. So @gtoison could not close that PR.

I suggest to update this token with another one created by @gtoison or other active members.
The requirements for this token is [noted in this README](https://github.com/spotbugs/sonar-findbugs/blob/master/.github/actions/sonar-update-center/README.md).

**Comment by gtoison** [comment]
@KengoTODA I think I lack the permission to add repository secrets

**Comment by gtoison** [comment]
Hello @hazendaz, maybe you can give me the permission to edit the repository secrets?

**Comment by gtoison** [comment]
Hello @iloveeclipse @hazendaz 
I do not have the permissions to edit the repository secrets.
We I release a new version we need to create a PR on a SonarSource repository to add the new version. This was automated by Kengo but it still uses the token he had saved. We would need to update that token so we stop bothering him

**Comment by hazendaz** [comment]
Sorry lost track you needed more access.  Will get you setup this weekend unless someone beats me to it.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by hazendaz** [comment]
@gtoison Had to look up instructions!  Think I finally got it.  You are listed as admin on that project now.  You should be able to do all you need.  If not let me know.

**Comment by gtoison** [comment]
Thanks, I have update the token!
