### ISSUE TITLE
Can not execute Findbugs 3.4.4 with Sonar-Scanner 3.0.0.702 (Android Gradle Project)

### ISSUE THREAD

**Issue by sherifkozman** [spotbugs/sonar-findbugs#89]
Running FindBugs 3.4.4 with Sonar Scaner always results a java.lang.IllegalStateException: Can not execute Findbugs

WARN: Findbugs needs sources to be compiled. Please build project before executing sonar or check the location of compiled classes to make it possible for Findbugs to analyse your project.

Binaries set to : 
sonar.binaries=app/build/intermediates/classes/debug

[findbugs-error-trace.txt](https://github.com/SonarQubeCommunity/sonar-findbugs/files/913811/findbugs-error-trace.txt)

**Comment by h3xstream** [comment]
It is potentially this bug in SonarQube : https://groups.google.com/forum/#!topic/sonarqube/1EBg4zgdPlg

**Comment by h3xstream** [comment]
Can you test with the official gradle plugin?
Sample configuration : https://github.com/find-sec-bugs/find-sec-bugs-demos/tree/master/android-insecure-bank-v2
