### ISSUE TITLE
Make "sonar-findbugs" compatible with SonarQube 10.4 "DownloadOnlyWhenRequired" feature

### ISSUE THREAD

**Issue by agigleux** [spotbugs/sonar-findbugs#957]
Hello,

I'm Alex, Product Manager at Sonar.

SonarQube 10.4 will come with a feature to only download Sonar analyzers and 3rd-party plugins when they are really required by the Scanner. To make this feature work, each analyzer or 3rd-party plugin should declare the list of languages on which they expect to raise issues through a new MANIFEST property called Plugin-RequiredForLanguages.

See https://community.sonarsource.com/t/the-sonarscanners-download-only-required-3rd-party-plugins/108156 for more details.

Regards

**Comment by gtoison** [comment]
This should be fixed by #958 but the build fails due to the jfrog/orchestrtator issue discussed here: https://community.sonarsource.com/t/community-plugins-can-no-longer-make-requests-to-jfrog-via-the-orchestrator-library/107955

**Comment by gtoison** [comment]
A new version of the plugin (version 4.2.7) was released with that new feature, please let me know if you see any issue!
