### ISSUE TITLE
Getting "Hard coded password found here" exception where (IMHO) it shouldn't 

### ISSUE THREAD

**Issue by sliric** [spotbugs/sonar-findbugs#987]
Why I'm getting the **Hard coded password found here** exception here:

`
@Value("${p12Name}")
  private String p12Name;

  @Value("${p12Alias}")
  private String p12Alias;

  @Value("${p12Password}")
  private String p12Token;
.............
    KeyStore keystore = KeyStore.getInstance("PKCS12");
    keystore.load(
        this.getClass().getClassLoader().getResourceAsStream(p12Name), p12Token.toCharArray());
    PrivateKey key = (PrivateKey) keystore.getKey(p12Alias, p12Token.toCharArray());
`

I’m getting this error in the line ‘keystore.load(’.
SQ version is 9.9 (build 65466)

This is the screenshot of this problem:
![image](https://github.com/spotbugs/sonar-findbugs/assets/90183084/df7a4098-bcb8-4ee7-ab41-fdce43dbb9fd)

**Comment by gtoison** [comment]
Hello, this rule is from [findsecbugs](https://find-sec-bugs.github.io/)
Before you report the issue there can you please say which version of the plugin you're using? So I check what's the corresponding version of findsecbugs

**Comment by sliric** [comment]
Sorry @gtoison I cannot find plugins version in SonarQube, is this the maybe helpful: 
<img width="1007" alt="image" src="https://github.com/spotbugs/sonar-findbugs/assets/90183084/53de9f1b-a74d-4535-9126-db97f7127678">

**Comment by gtoison** [comment]
The plugin version should be visible in SonarQube's marketplace page where all the plugins are visible (you need SonarQube admin rights to see that page I think)

**Comment by sliric** [comment]
It’s version 1.12.0

**Comment by gtoison** [comment]
Thanks, it would be helpful to report the false positive on https://github.com/find-sec-bugs/find-sec-bugs/issues with a minimal code example reproducing the problem. The code sample you have posted does not have the imports, I guess these are Spring classes but it's not always obvious ;)

**Comment by sliric** [comment]
Ok, here it is => https://github.com/find-sec-bugs/find-sec-bugs/issues/731

**Comment by hazendaz** [comment]
closing issue as not related to this project, open issue is still open at find sec bugs, we cannot do anything here.
